/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.j2ee.session;

import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;
import org.apache.log4j.Logger;

public class MessagesSessionBean implements SessionBean
{
	private MessagesDao daoImpl = createDao();

	protected static final Logger logger = Logger.getLogger( MessagesSessionBean.class );

	/** 
	 * Inserts a new row in the MESSAGES table.
	 */
	public MessagesPk insert(Messages dto) throws MessagesDaoException
	{
		try {
			return daoImpl.insert(dto);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the MESSAGES table.
	 */
	public void update(MessagesPk pk, Messages dto) throws MessagesDaoException
	{
		try {
			daoImpl.update(pk, dto);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the MESSAGES table.
	 */
	public void delete(MessagesPk pk) throws MessagesDaoException
	{
		try {
			daoImpl.delete(pk);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Returns the rows from the MESSAGES table that matches the specified primary-key value.
	 */
	public Messages findByPrimaryKey(MessagesPk pk) throws MessagesDaoException
	{
		return findByPrimaryKey( pk.getMessageId() );
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param messageId
	 * @throws MessagesDaoException
	 * @return Messages
	 */
	public Messages findByPrimaryKey(long messageId) throws MessagesDaoException
	{
		try {
			return daoImpl.findByPrimaryKey(messageId);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findAll() throws MessagesDaoException
	{
		try {
			return daoImpl.findAll();
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereMessageIdEquals'
	 * 
	 * @param messageId
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereMessageIdEquals(long messageId) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereMessageIdEquals(messageId);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereTypeEquals'
	 * 
	 * @param type
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereTypeEquals(String type) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereTypeEquals(type);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereStartTimeEquals'
	 * 
	 * @param startTime
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereStartTimeEquals(Date startTime) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereStartTimeEquals(startTime);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereEndTimeEquals'
	 * 
	 * @param endTime
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereEndTimeEquals(Date endTime) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereEndTimeEquals(endTime);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereModTimeEquals'
	 * 
	 * @param modTime
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereModTimeEquals(Date modTime) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereModTimeEquals(modTime);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereTitleEquals'
	 * 
	 * @param title
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereTitleEquals(String title) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereTitleEquals(title);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereContentsEquals'
	 * 
	 * @param contents
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereContentsEquals(String contents) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereContentsEquals(contents);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereSummaryEquals'
	 * 
	 * @param summary
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereSummaryEquals(String summary) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereSummaryEquals(summary);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWherePriorityEquals'
	 * 
	 * @param priority
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWherePriorityEquals(String priority) throws MessagesDaoException
	{
		try {
			return daoImpl.findWherePriorityEquals(priority);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWherePopupDurationEquals'
	 * 
	 * @param popupDuration
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWherePopupDurationEquals(long popupDuration) throws MessagesDaoException
	{
		try {
			return daoImpl.findWherePopupDurationEquals(popupDuration);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereClickDestinationUrlEquals'
	 * 
	 * @param clickDestinationUrl
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereClickDestinationUrlEquals(String clickDestinationUrl) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereClickDestinationUrlEquals(clickDestinationUrl);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereDestinationEquals'
	 * 
	 * @param destination
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereDestinationEquals(String destination) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereDestinationEquals(destination);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereGroupNameEquals'
	 * 
	 * @param groupName
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereGroupNameEquals(String groupName) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereGroupNameEquals(groupName);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereViveIdEquals'
	 * 
	 * @param viveId
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findWhereViveIdEquals(String viveId) throws MessagesDaoException
	{
		try {
			return daoImpl.findWhereViveIdEquals(viveId);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param arg
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findByDynamicSelect(String sql, Object[] arg) throws MessagesDaoException
	{
		try {
			return daoImpl.findByDynamicSelect(sql, arg);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param arg
	 * @throws MessagesDaoException
	 * @return Messages[]
	 */
	public Messages[] findByDynamicWhere(String sql, Object[] arg) throws MessagesDaoException
	{
		try {
			return daoImpl.findByDynamicWhere(sql, arg);
		}
		catch (MessagesDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new MessagesDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'ejbActivate'
	 * 
	 */
	public void ejbActivate()
	{
	}

	/**
	 * Method 'ejbPassivate'
	 * 
	 */
	public void ejbPassivate()
	{
	}

	/**
	 * Method 'ejbCreate'
	 * 
	 */
	public void ejbCreate()
	{
	}

	/**
	 * Method 'ejbRemove'
	 * 
	 */
	public void ejbRemove()
	{
	}

	/**
	 * Method 'setSessionContext'
	 * 
	 * @param ctx
	 */
	public void setSessionContext(SessionContext ctx)
	{
	}

	/**
	 * Method 'unsetSessionContext'
	 * 
	 */
	public void unsetSessionContext()
	{
	}

	/**
	 * Method 'createDao'
	 * 
	 * @return MessagesDao
	 */
	private MessagesDao createDao()
	{
		return MessagesDaoFactory.create();
	}

}
