/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.j2ee.session;

import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;
import org.apache.log4j.Logger;

public class ModifiedDataSessionBean implements SessionBean
{
	private ModifiedDataDao daoImpl = createDao();

	protected static final Logger logger = Logger.getLogger( ModifiedDataSessionBean.class );

	/** 
	 * Inserts a new row in the MODIFIED_DATA table.
	 */
	public ModifiedDataPk insert(ModifiedData dto) throws ModifiedDataDaoException
	{
		try {
			return daoImpl.insert(dto);
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the MODIFIED_DATA table.
	 */
	public void update(ModifiedDataPk pk, ModifiedData dto) throws ModifiedDataDaoException
	{
		try {
			daoImpl.update(pk, dto);
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the MODIFIED_DATA table.
	 */
	public void delete(ModifiedDataPk pk) throws ModifiedDataDaoException
	{
		try {
			daoImpl.delete(pk);
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Returns the rows from the MODIFIED_DATA table that matches the specified primary-key value.
	 */
	public ModifiedData findByPrimaryKey(ModifiedDataPk pk) throws ModifiedDataDaoException
	{
		return findByPrimaryKey( pk.getModifiedDataId() );
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param modifiedDataId
	 * @throws ModifiedDataDaoException
	 * @return ModifiedData
	 */
	public ModifiedData findByPrimaryKey(long modifiedDataId) throws ModifiedDataDaoException
	{
		try {
			return daoImpl.findByPrimaryKey(modifiedDataId);
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws ModifiedDataDaoException
	 * @return ModifiedData[]
	 */
	public ModifiedData[] findAll() throws ModifiedDataDaoException
	{
		try {
			return daoImpl.findAll();
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereModifiedDataIdEquals'
	 * 
	 * @param modifiedDataId
	 * @throws ModifiedDataDaoException
	 * @return ModifiedData[]
	 */
	public ModifiedData[] findWhereModifiedDataIdEquals(long modifiedDataId) throws ModifiedDataDaoException
	{
		try {
			return daoImpl.findWhereModifiedDataIdEquals(modifiedDataId);
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereCustomerIdEquals'
	 * 
	 * @param customerId
	 * @throws ModifiedDataDaoException
	 * @return ModifiedData[]
	 */
	public ModifiedData[] findWhereCustomerIdEquals(long customerId) throws ModifiedDataDaoException
	{
		try {
			return daoImpl.findWhereCustomerIdEquals(customerId);
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereModifiedTimeEquals'
	 * 
	 * @param modifiedTime
	 * @throws ModifiedDataDaoException
	 * @return ModifiedData[]
	 */
	public ModifiedData[] findWhereModifiedTimeEquals(Date modifiedTime) throws ModifiedDataDaoException
	{
		try {
			return daoImpl.findWhereModifiedTimeEquals(modifiedTime);
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param arg
	 * @throws ModifiedDataDaoException
	 * @return ModifiedData[]
	 */
	public ModifiedData[] findByDynamicSelect(String sql, Object[] arg) throws ModifiedDataDaoException
	{
		try {
			return daoImpl.findByDynamicSelect(sql, arg);
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param arg
	 * @throws ModifiedDataDaoException
	 * @return ModifiedData[]
	 */
	public ModifiedData[] findByDynamicWhere(String sql, Object[] arg) throws ModifiedDataDaoException
	{
		try {
			return daoImpl.findByDynamicWhere(sql, arg);
		}
		catch (ModifiedDataDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ModifiedDataDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'ejbActivate'
	 * 
	 */
	public void ejbActivate()
	{
	}

	/**
	 * Method 'ejbPassivate'
	 * 
	 */
	public void ejbPassivate()
	{
	}

	/**
	 * Method 'ejbCreate'
	 * 
	 */
	public void ejbCreate()
	{
	}

	/**
	 * Method 'ejbRemove'
	 * 
	 */
	public void ejbRemove()
	{
	}

	/**
	 * Method 'setSessionContext'
	 * 
	 * @param ctx
	 */
	public void setSessionContext(SessionContext ctx)
	{
	}

	/**
	 * Method 'unsetSessionContext'
	 * 
	 */
	public void unsetSessionContext()
	{
	}

	/**
	 * Method 'createDao'
	 * 
	 * @return ModifiedDataDao
	 */
	private ModifiedDataDao createDao()
	{
		return ModifiedDataDaoFactory.create();
	}

}
