/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.j2ee.session;

import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;
import org.apache.log4j.Logger;

public class SnmpqinfoSessionBean implements SessionBean
{
	private SnmpqinfoDao daoImpl = createDao();

	protected static final Logger logger = Logger.getLogger( SnmpqinfoSessionBean.class );

	/** 
	 * Inserts a new row in the SNMPQINFO table.
	 */
	public SnmpqinfoPk insert(Snmpqinfo dto) throws SnmpqinfoDaoException
	{
		try {
			return daoImpl.insert(dto);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the SNMPQINFO table.
	 */
	public void update(SnmpqinfoPk pk, Snmpqinfo dto) throws SnmpqinfoDaoException
	{
		try {
			daoImpl.update(pk, dto);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the SNMPQINFO table.
	 */
	public void delete(SnmpqinfoPk pk) throws SnmpqinfoDaoException
	{
		try {
			daoImpl.delete(pk);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Returns the rows from the SNMPQINFO table that matches the specified primary-key value.
	 */
	public Snmpqinfo findByPrimaryKey(SnmpqinfoPk pk) throws SnmpqinfoDaoException
	{
		return findByPrimaryKey( pk.getSnmpqinfoId() );
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param snmpqinfoId
	 * @throws SnmpqinfoDaoException
	 * @return Snmpqinfo
	 */
	public Snmpqinfo findByPrimaryKey(long snmpqinfoId) throws SnmpqinfoDaoException
	{
		try {
			return daoImpl.findByPrimaryKey(snmpqinfoId);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws SnmpqinfoDaoException
	 * @return Snmpqinfo[]
	 */
	public Snmpqinfo[] findAll() throws SnmpqinfoDaoException
	{
		try {
			return daoImpl.findAll();
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereSnmpqinfoIdEquals'
	 * 
	 * @param snmpqinfoId
	 * @throws SnmpqinfoDaoException
	 * @return Snmpqinfo[]
	 */
	public Snmpqinfo[] findWhereSnmpqinfoIdEquals(long snmpqinfoId) throws SnmpqinfoDaoException
	{
		try {
			return daoImpl.findWhereSnmpqinfoIdEquals(snmpqinfoId);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereNetworkinfoIdEquals'
	 * 
	 * @param networkinfoId
	 * @throws SnmpqinfoDaoException
	 * @return Snmpqinfo[]
	 */
	public Snmpqinfo[] findWhereNetworkinfoIdEquals(long networkinfoId) throws SnmpqinfoDaoException
	{
		try {
			return daoImpl.findWhereNetworkinfoIdEquals(networkinfoId);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 * @throws SnmpqinfoDaoException
	 * @return Snmpqinfo[]
	 */
	public Snmpqinfo[] findWhereNameEquals(String name) throws SnmpqinfoDaoException
	{
		try {
			return daoImpl.findWhereNameEquals(name);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereTreeEquals'
	 * 
	 * @param tree
	 * @throws SnmpqinfoDaoException
	 * @return Snmpqinfo[]
	 */
	public Snmpqinfo[] findWhereTreeEquals(String tree) throws SnmpqinfoDaoException
	{
		try {
			return daoImpl.findWhereTreeEquals(tree);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param arg
	 * @throws SnmpqinfoDaoException
	 * @return Snmpqinfo[]
	 */
	public Snmpqinfo[] findByDynamicSelect(String sql, Object[] arg) throws SnmpqinfoDaoException
	{
		try {
			return daoImpl.findByDynamicSelect(sql, arg);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param arg
	 * @throws SnmpqinfoDaoException
	 * @return Snmpqinfo[]
	 */
	public Snmpqinfo[] findByDynamicWhere(String sql, Object[] arg) throws SnmpqinfoDaoException
	{
		try {
			return daoImpl.findByDynamicWhere(sql, arg);
		}
		catch (SnmpqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new SnmpqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'ejbActivate'
	 * 
	 */
	public void ejbActivate()
	{
	}

	/**
	 * Method 'ejbPassivate'
	 * 
	 */
	public void ejbPassivate()
	{
	}

	/**
	 * Method 'ejbCreate'
	 * 
	 */
	public void ejbCreate()
	{
	}

	/**
	 * Method 'ejbRemove'
	 * 
	 */
	public void ejbRemove()
	{
	}

	/**
	 * Method 'setSessionContext'
	 * 
	 * @param ctx
	 */
	public void setSessionContext(SessionContext ctx)
	{
	}

	/**
	 * Method 'unsetSessionContext'
	 * 
	 */
	public void unsetSessionContext()
	{
	}

	/**
	 * Method 'createDao'
	 * 
	 * @return SnmpqinfoDao
	 */
	private SnmpqinfoDao createDao()
	{
		return SnmpqinfoDaoFactory.create();
	}

}
