/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.j2ee.session;

import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;
import org.apache.log4j.Logger;

public class TelesalesOrgsSessionBean implements SessionBean
{
	private TelesalesOrgsDao daoImpl = createDao();

	protected static final Logger logger = Logger.getLogger( TelesalesOrgsSessionBean.class );

	/** 
	 * Inserts a new row in the TELESALES_ORGS table.
	 */
	public TelesalesOrgsPk insert(TelesalesOrgs dto) throws TelesalesOrgsDaoException
	{
		try {
			return daoImpl.insert(dto);
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the TELESALES_ORGS table.
	 */
	public void update(TelesalesOrgsPk pk, TelesalesOrgs dto) throws TelesalesOrgsDaoException
	{
		try {
			daoImpl.update(pk, dto);
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the TELESALES_ORGS table.
	 */
	public void delete(TelesalesOrgsPk pk) throws TelesalesOrgsDaoException
	{
		try {
			daoImpl.delete(pk);
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Returns the rows from the TELESALES_ORGS table that matches the specified primary-key value.
	 */
	public TelesalesOrgs findByPrimaryKey(TelesalesOrgsPk pk) throws TelesalesOrgsDaoException
	{
		return findByPrimaryKey( pk.getOrgId() );
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param orgId
	 * @throws TelesalesOrgsDaoException
	 * @return TelesalesOrgs
	 */
	public TelesalesOrgs findByPrimaryKey(long orgId) throws TelesalesOrgsDaoException
	{
		try {
			return daoImpl.findByPrimaryKey(orgId);
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws TelesalesOrgsDaoException
	 * @return TelesalesOrgs[]
	 */
	public TelesalesOrgs[] findAll() throws TelesalesOrgsDaoException
	{
		try {
			return daoImpl.findAll();
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereOrgIdEquals'
	 * 
	 * @param orgId
	 * @throws TelesalesOrgsDaoException
	 * @return TelesalesOrgs[]
	 */
	public TelesalesOrgs[] findWhereOrgIdEquals(long orgId) throws TelesalesOrgsDaoException
	{
		try {
			return daoImpl.findWhereOrgIdEquals(orgId);
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereOrgNameEquals'
	 * 
	 * @param orgName
	 * @throws TelesalesOrgsDaoException
	 * @return TelesalesOrgs[]
	 */
	public TelesalesOrgs[] findWhereOrgNameEquals(String orgName) throws TelesalesOrgsDaoException
	{
		try {
			return daoImpl.findWhereOrgNameEquals(orgName);
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereConfigValueEquals'
	 * 
	 * @param configValue
	 * @throws TelesalesOrgsDaoException
	 * @return TelesalesOrgs[]
	 */
	public TelesalesOrgs[] findWhereConfigValueEquals(String configValue) throws TelesalesOrgsDaoException
	{
		try {
			return daoImpl.findWhereConfigValueEquals(configValue);
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param arg
	 * @throws TelesalesOrgsDaoException
	 * @return TelesalesOrgs[]
	 */
	public TelesalesOrgs[] findByDynamicSelect(String sql, Object[] arg) throws TelesalesOrgsDaoException
	{
		try {
			return daoImpl.findByDynamicSelect(sql, arg);
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param arg
	 * @throws TelesalesOrgsDaoException
	 * @return TelesalesOrgs[]
	 */
	public TelesalesOrgs[] findByDynamicWhere(String sql, Object[] arg) throws TelesalesOrgsDaoException
	{
		try {
			return daoImpl.findByDynamicWhere(sql, arg);
		}
		catch (TelesalesOrgsDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesOrgsDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'ejbActivate'
	 * 
	 */
	public void ejbActivate()
	{
	}

	/**
	 * Method 'ejbPassivate'
	 * 
	 */
	public void ejbPassivate()
	{
	}

	/**
	 * Method 'ejbCreate'
	 * 
	 */
	public void ejbCreate()
	{
	}

	/**
	 * Method 'ejbRemove'
	 * 
	 */
	public void ejbRemove()
	{
	}

	/**
	 * Method 'setSessionContext'
	 * 
	 * @param ctx
	 */
	public void setSessionContext(SessionContext ctx)
	{
	}

	/**
	 * Method 'unsetSessionContext'
	 * 
	 */
	public void unsetSessionContext()
	{
	}

	/**
	 * Method 'createDao'
	 * 
	 * @return TelesalesOrgsDao
	 */
	private TelesalesOrgsDao createDao()
	{
		return TelesalesOrgsDaoFactory.create();
	}

}
