/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.j2ee.session;

import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;
import org.apache.log4j.Logger;

public class WnqinfoSessionBean implements SessionBean
{
	private WnqinfoDao daoImpl = createDao();

	protected static final Logger logger = Logger.getLogger( WnqinfoSessionBean.class );

	/** 
	 * Inserts a new row in the WNQINFO table.
	 */
	public WnqinfoPk insert(Wnqinfo dto) throws WnqinfoDaoException
	{
		try {
			return daoImpl.insert(dto);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the WNQINFO table.
	 */
	public void update(WnqinfoPk pk, Wnqinfo dto) throws WnqinfoDaoException
	{
		try {
			daoImpl.update(pk, dto);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the WNQINFO table.
	 */
	public void delete(WnqinfoPk pk) throws WnqinfoDaoException
	{
		try {
			daoImpl.delete(pk);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Returns the rows from the WNQINFO table that matches the specified primary-key value.
	 */
	public Wnqinfo findByPrimaryKey(WnqinfoPk pk) throws WnqinfoDaoException
	{
		return findByPrimaryKey( pk.getWnqinfoId() );
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param wnqinfoId
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo
	 */
	public Wnqinfo findByPrimaryKey(long wnqinfoId) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findByPrimaryKey(wnqinfoId);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findAll() throws WnqinfoDaoException
	{
		try {
			return daoImpl.findAll();
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereWnqinfoIdEquals'
	 * 
	 * @param wnqinfoId
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereWnqinfoIdEquals(long wnqinfoId) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereWnqinfoIdEquals(wnqinfoId);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereNetworkinfoIdEquals'
	 * 
	 * @param networkinfoId
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereNetworkinfoIdEquals(long networkinfoId) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereNetworkinfoIdEquals(networkinfoId);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereProviderEquals'
	 * 
	 * @param provider
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereProviderEquals(String provider) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereProviderEquals(provider);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereRemotenameEquals'
	 * 
	 * @param remotename
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereRemotenameEquals(String remotename) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereRemotenameEquals(remotename);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereLocalnameEquals'
	 * 
	 * @param localname
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereLocalnameEquals(String localname) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereLocalnameEquals(localname);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereIpaddressEquals'
	 * 
	 * @param ipaddress
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereIpaddressEquals(String ipaddress) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereIpaddressEquals(ipaddress);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereWnqcommentEquals'
	 * 
	 * @param wnqcomment
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereWnqcommentEquals(String wnqcomment) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereWnqcommentEquals(wnqcomment);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereDisplaytypeEquals'
	 * 
	 * @param displaytype
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereDisplaytypeEquals(String displaytype) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereDisplaytypeEquals(displaytype);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereWnqscopeEquals'
	 * 
	 * @param wnqscope
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereWnqscopeEquals(String wnqscope) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereWnqscopeEquals(wnqscope);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereWnqtypeEquals'
	 * 
	 * @param wnqtype
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereWnqtypeEquals(String wnqtype) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereWnqtypeEquals(wnqtype);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereWnqusageEquals'
	 * 
	 * @param wnqusage
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findWhereWnqusageEquals(String wnqusage) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findWhereWnqusageEquals(wnqusage);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param arg
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findByDynamicSelect(String sql, Object[] arg) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findByDynamicSelect(sql, arg);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param arg
	 * @throws WnqinfoDaoException
	 * @return Wnqinfo[]
	 */
	public Wnqinfo[] findByDynamicWhere(String sql, Object[] arg) throws WnqinfoDaoException
	{
		try {
			return daoImpl.findByDynamicWhere(sql, arg);
		}
		catch (WnqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WnqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'ejbActivate'
	 * 
	 */
	public void ejbActivate()
	{
	}

	/**
	 * Method 'ejbPassivate'
	 * 
	 */
	public void ejbPassivate()
	{
	}

	/**
	 * Method 'ejbCreate'
	 * 
	 */
	public void ejbCreate()
	{
	}

	/**
	 * Method 'ejbRemove'
	 * 
	 */
	public void ejbRemove()
	{
	}

	/**
	 * Method 'setSessionContext'
	 * 
	 * @param ctx
	 */
	public void setSessionContext(SessionContext ctx)
	{
	}

	/**
	 * Method 'unsetSessionContext'
	 * 
	 */
	public void unsetSessionContext()
	{
	}

	/**
	 * Method 'createDao'
	 * 
	 * @return WnqinfoDao
	 */
	private WnqinfoDao createDao()
	{
		return WnqinfoDaoFactory.create();
	}

}
