/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.factory;

import java.sql.Connection;
import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.jdbc.*;

public class SnmpqinfoDaoFactory
{
	private static final SnmpqinfoDaoImpl dao = new SnmpqinfoDaoImpl();

	/**
	 * Method 'create'
	 * 
	 * @return SnmpqinfoDao
	 */
	public static SnmpqinfoDao create()
	{
		return dao;
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return SnmpqinfoDao
	 */
	public static SnmpqinfoDao create(Connection conn)
	{
		return new SnmpqinfoDaoImpl( conn );
	}

}
