/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.factory;

import java.sql.Connection;
import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.jdbc.*;

public class TelesalesCallSourceDaoFactory
{
	private static final TelesalesCallSourceDaoImpl dao = new TelesalesCallSourceDaoImpl();

	/**
	 * Method 'create'
	 * 
	 * @return TelesalesCallSourceDao
	 */
	public static TelesalesCallSourceDao create()
	{
		return dao;
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return TelesalesCallSourceDao
	 */
	public static TelesalesCallSourceDao create(Connection conn)
	{
		return new TelesalesCallSourceDaoImpl( conn );
	}

}
