/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.dto;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Messages implements Serializable
{
	/** 
	 * This attribute maps to the column MESSAGE_ID in the MESSAGES table.
	 */
	private long messageId;

	/** 
	 * This attribute represents whether the attribute messageId has been modified since being read from the database.
	 */
	private boolean messageIdModified = false;

	/** 
	 * This attribute maps to the column TYPE in the MESSAGES table.
	 */
	private String type;

	/** 
	 * This attribute represents whether the attribute type has been modified since being read from the database.
	 */
	private boolean typeModified = false;

	/** 
	 * This attribute maps to the column START_TIME in the MESSAGES table.
	 */
	private Date startTime;

	/** 
	 * This attribute represents whether the attribute startTime has been modified since being read from the database.
	 */
	private boolean startTimeModified = false;

	/** 
	 * This attribute maps to the column END_TIME in the MESSAGES table.
	 */
	private Date endTime;

	/** 
	 * This attribute represents whether the attribute endTime has been modified since being read from the database.
	 */
	private boolean endTimeModified = false;

	/** 
	 * This attribute maps to the column MOD_TIME in the MESSAGES table.
	 */
	private Date modTime;

	/** 
	 * This attribute represents whether the attribute modTime has been modified since being read from the database.
	 */
	private boolean modTimeModified = false;

	/** 
	 * This attribute maps to the column TITLE in the MESSAGES table.
	 */
	private String title;

	/** 
	 * This attribute represents whether the attribute title has been modified since being read from the database.
	 */
	private boolean titleModified = false;

	/** 
	 * This attribute maps to the column CONTENTS in the MESSAGES table.
	 */
	private String contents;

	/** 
	 * This attribute represents whether the attribute contents has been modified since being read from the database.
	 */
	private boolean contentsModified = false;

	/** 
	 * This attribute maps to the column SUMMARY in the MESSAGES table.
	 */
	private String summary;

	/** 
	 * This attribute represents whether the attribute summary has been modified since being read from the database.
	 */
	private boolean summaryModified = false;

	/** 
	 * This attribute maps to the column PRIORITY in the MESSAGES table.
	 */
	private String priority;

	/** 
	 * This attribute represents whether the attribute priority has been modified since being read from the database.
	 */
	private boolean priorityModified = false;

	/** 
	 * This attribute maps to the column POPUP_DURATION in the MESSAGES table.
	 */
	private long popupDuration;

	/** 
	 * This attribute represents whether the attribute popupDuration has been modified since being read from the database.
	 */
	private boolean popupDurationModified = false;

	/** 
	 * This attribute maps to the column CLICK_DESTINATION_URL in the MESSAGES table.
	 */
	private String clickDestinationUrl;

	/** 
	 * This attribute represents whether the attribute clickDestinationUrl has been modified since being read from the database.
	 */
	private boolean clickDestinationUrlModified = false;

	/** 
	 * This attribute maps to the column DESTINATION in the MESSAGES table.
	 */
	private String destination;

	/** 
	 * This attribute represents whether the attribute destination has been modified since being read from the database.
	 */
	private boolean destinationModified = false;

	/** 
	 * This attribute maps to the column GROUP_NAME in the MESSAGES table.
	 */
	private String groupName;

	/** 
	 * This attribute represents whether the attribute groupName has been modified since being read from the database.
	 */
	private boolean groupNameModified = false;

	/** 
	 * This attribute maps to the column VIVE_ID in the MESSAGES table.
	 */
	private String viveId;

	/** 
	 * This attribute represents whether the attribute viveId has been modified since being read from the database.
	 */
	private boolean viveIdModified = false;

	/**
	 * Method 'Messages'
	 * 
	 */
	public Messages()
	{
	}

	/**
	 * Method 'getMessageId'
	 * 
	 * @return long
	 */
	public long getMessageId()
	{
		return messageId;
	}

	/**
	 * Method 'setMessageId'
	 * 
	 * @param messageId
	 */
	public void setMessageId(long messageId)
	{
		this.messageId = messageId;
		setMessageIdModified( true );
	}

	/** 
	 * Sets the value of messageIdModified
	 */
	public void setMessageIdModified(boolean messageIdModified)
	{
		this.messageIdModified = messageIdModified;
	}

	/** 
	 * Gets the value of messageIdModified
	 */
	public boolean isMessageIdModified()
	{
		return messageIdModified;
	}

	/**
	 * Method 'getType'
	 * 
	 * @return String
	 */
	public String getType()
	{
		return type;
	}

	/**
	 * Method 'setType'
	 * 
	 * @param type
	 */
	public void setType(String type)
	{
		this.type = type;
		setTypeModified( true );
	}

	/** 
	 * Sets the value of typeModified
	 */
	public void setTypeModified(boolean typeModified)
	{
		this.typeModified = typeModified;
	}

	/** 
	 * Gets the value of typeModified
	 */
	public boolean isTypeModified()
	{
		return typeModified;
	}

	/**
	 * Method 'getStartTime'
	 * 
	 * @return Date
	 */
	public Date getStartTime()
	{
		return startTime;
	}

	/**
	 * Method 'setStartTime'
	 * 
	 * @param startTime
	 */
	public void setStartTime(Date startTime)
	{
		this.startTime = startTime;
		setStartTimeModified( true );
	}

	/** 
	 * Sets the value of startTimeModified
	 */
	public void setStartTimeModified(boolean startTimeModified)
	{
		this.startTimeModified = startTimeModified;
	}

	/** 
	 * Gets the value of startTimeModified
	 */
	public boolean isStartTimeModified()
	{
		return startTimeModified;
	}

	/**
	 * Method 'getEndTime'
	 * 
	 * @return Date
	 */
	public Date getEndTime()
	{
		return endTime;
	}

	/**
	 * Method 'setEndTime'
	 * 
	 * @param endTime
	 */
	public void setEndTime(Date endTime)
	{
		this.endTime = endTime;
		setEndTimeModified( true );
	}

	/** 
	 * Sets the value of endTimeModified
	 */
	public void setEndTimeModified(boolean endTimeModified)
	{
		this.endTimeModified = endTimeModified;
	}

	/** 
	 * Gets the value of endTimeModified
	 */
	public boolean isEndTimeModified()
	{
		return endTimeModified;
	}

	/**
	 * Method 'getModTime'
	 * 
	 * @return Date
	 */
	public Date getModTime()
	{
		return modTime;
	}

	/**
	 * Method 'setModTime'
	 * 
	 * @param modTime
	 */
	public void setModTime(Date modTime)
	{
		this.modTime = modTime;
		setModTimeModified( true );
	}

	/** 
	 * Sets the value of modTimeModified
	 */
	public void setModTimeModified(boolean modTimeModified)
	{
		this.modTimeModified = modTimeModified;
	}

	/** 
	 * Gets the value of modTimeModified
	 */
	public boolean isModTimeModified()
	{
		return modTimeModified;
	}

	/**
	 * Method 'getTitle'
	 * 
	 * @return String
	 */
	public String getTitle()
	{
		return title;
	}

	/**
	 * Method 'setTitle'
	 * 
	 * @param title
	 */
	public void setTitle(String title)
	{
		this.title = title;
		setTitleModified( true );
	}

	/** 
	 * Sets the value of titleModified
	 */
	public void setTitleModified(boolean titleModified)
	{
		this.titleModified = titleModified;
	}

	/** 
	 * Gets the value of titleModified
	 */
	public boolean isTitleModified()
	{
		return titleModified;
	}

	/**
	 * Method 'getContents'
	 * 
	 * @return String
	 */
	public String getContents()
	{
		return contents;
	}

	/**
	 * Method 'setContents'
	 * 
	 * @param contents
	 */
	public void setContents(String contents)
	{
		this.contents = contents;
		setContentsModified( true );
	}

	/** 
	 * Sets the value of contentsModified
	 */
	public void setContentsModified(boolean contentsModified)
	{
		this.contentsModified = contentsModified;
	}

	/** 
	 * Gets the value of contentsModified
	 */
	public boolean isContentsModified()
	{
		return contentsModified;
	}

	/**
	 * Method 'getSummary'
	 * 
	 * @return String
	 */
	public String getSummary()
	{
		return summary;
	}

	/**
	 * Method 'setSummary'
	 * 
	 * @param summary
	 */
	public void setSummary(String summary)
	{
		this.summary = summary;
		setSummaryModified( true );
	}

	/** 
	 * Sets the value of summaryModified
	 */
	public void setSummaryModified(boolean summaryModified)
	{
		this.summaryModified = summaryModified;
	}

	/** 
	 * Gets the value of summaryModified
	 */
	public boolean isSummaryModified()
	{
		return summaryModified;
	}

	/**
	 * Method 'getPriority'
	 * 
	 * @return String
	 */
	public String getPriority()
	{
		return priority;
	}

	/**
	 * Method 'setPriority'
	 * 
	 * @param priority
	 */
	public void setPriority(String priority)
	{
		this.priority = priority;
		setPriorityModified( true );
	}

	/** 
	 * Sets the value of priorityModified
	 */
	public void setPriorityModified(boolean priorityModified)
	{
		this.priorityModified = priorityModified;
	}

	/** 
	 * Gets the value of priorityModified
	 */
	public boolean isPriorityModified()
	{
		return priorityModified;
	}

	/**
	 * Method 'getPopupDuration'
	 * 
	 * @return long
	 */
	public long getPopupDuration()
	{
		return popupDuration;
	}

	/**
	 * Method 'setPopupDuration'
	 * 
	 * @param popupDuration
	 */
	public void setPopupDuration(long popupDuration)
	{
		this.popupDuration = popupDuration;
		setPopupDurationModified( true );
	}

	/** 
	 * Sets the value of popupDurationModified
	 */
	public void setPopupDurationModified(boolean popupDurationModified)
	{
		this.popupDurationModified = popupDurationModified;
	}

	/** 
	 * Gets the value of popupDurationModified
	 */
	public boolean isPopupDurationModified()
	{
		return popupDurationModified;
	}

	/**
	 * Method 'getClickDestinationUrl'
	 * 
	 * @return String
	 */
	public String getClickDestinationUrl()
	{
		return clickDestinationUrl;
	}

	/**
	 * Method 'setClickDestinationUrl'
	 * 
	 * @param clickDestinationUrl
	 */
	public void setClickDestinationUrl(String clickDestinationUrl)
	{
		this.clickDestinationUrl = clickDestinationUrl;
		setClickDestinationUrlModified( true );
	}

	/** 
	 * Sets the value of clickDestinationUrlModified
	 */
	public void setClickDestinationUrlModified(boolean clickDestinationUrlModified)
	{
		this.clickDestinationUrlModified = clickDestinationUrlModified;
	}

	/** 
	 * Gets the value of clickDestinationUrlModified
	 */
	public boolean isClickDestinationUrlModified()
	{
		return clickDestinationUrlModified;
	}

	/**
	 * Method 'getDestination'
	 * 
	 * @return String
	 */
	public String getDestination()
	{
		return destination;
	}

	/**
	 * Method 'setDestination'
	 * 
	 * @param destination
	 */
	public void setDestination(String destination)
	{
		this.destination = destination;
		setDestinationModified( true );
	}

	/** 
	 * Sets the value of destinationModified
	 */
	public void setDestinationModified(boolean destinationModified)
	{
		this.destinationModified = destinationModified;
	}

	/** 
	 * Gets the value of destinationModified
	 */
	public boolean isDestinationModified()
	{
		return destinationModified;
	}

	/**
	 * Method 'getGroupName'
	 * 
	 * @return String
	 */
	public String getGroupName()
	{
		return groupName;
	}

	/**
	 * Method 'setGroupName'
	 * 
	 * @param groupName
	 */
	public void setGroupName(String groupName)
	{
		this.groupName = groupName;
		setGroupNameModified( true );
	}

	/** 
	 * Sets the value of groupNameModified
	 */
	public void setGroupNameModified(boolean groupNameModified)
	{
		this.groupNameModified = groupNameModified;
	}

	/** 
	 * Gets the value of groupNameModified
	 */
	public boolean isGroupNameModified()
	{
		return groupNameModified;
	}

	/**
	 * Method 'getViveId'
	 * 
	 * @return String
	 */
	public String getViveId()
	{
		return viveId;
	}

	/**
	 * Method 'setViveId'
	 * 
	 * @param viveId
	 */
	public void setViveId(String viveId)
	{
		this.viveId = viveId;
		setViveIdModified( true );
	}

	/** 
	 * Sets the value of viveIdModified
	 */
	public void setViveIdModified(boolean viveIdModified)
	{
		this.viveIdModified = viveIdModified;
	}

	/** 
	 * Gets the value of viveIdModified
	 */
	public boolean isViveIdModified()
	{
		return viveIdModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Messages)) {
			return false;
		}
		
		final Messages _cast = (Messages) _other;
		if (messageId != _cast.messageId) {
			return false;
		}
		
		if (messageIdModified != _cast.messageIdModified) {
			return false;
		}
		
		if (type == null ? _cast.type != type : !type.equals( _cast.type )) {
			return false;
		}
		
		if (typeModified != _cast.typeModified) {
			return false;
		}
		
		if (startTime == null ? _cast.startTime != startTime : !startTime.equals( _cast.startTime )) {
			return false;
		}
		
		if (startTimeModified != _cast.startTimeModified) {
			return false;
		}
		
		if (endTime == null ? _cast.endTime != endTime : !endTime.equals( _cast.endTime )) {
			return false;
		}
		
		if (endTimeModified != _cast.endTimeModified) {
			return false;
		}
		
		if (modTime == null ? _cast.modTime != modTime : !modTime.equals( _cast.modTime )) {
			return false;
		}
		
		if (modTimeModified != _cast.modTimeModified) {
			return false;
		}
		
		if (title == null ? _cast.title != title : !title.equals( _cast.title )) {
			return false;
		}
		
		if (titleModified != _cast.titleModified) {
			return false;
		}
		
		if (contents == null ? _cast.contents != contents : !contents.equals( _cast.contents )) {
			return false;
		}
		
		if (contentsModified != _cast.contentsModified) {
			return false;
		}
		
		if (summary == null ? _cast.summary != summary : !summary.equals( _cast.summary )) {
			return false;
		}
		
		if (summaryModified != _cast.summaryModified) {
			return false;
		}
		
		if (priority == null ? _cast.priority != priority : !priority.equals( _cast.priority )) {
			return false;
		}
		
		if (priorityModified != _cast.priorityModified) {
			return false;
		}
		
		if (popupDuration != _cast.popupDuration) {
			return false;
		}
		
		if (popupDurationModified != _cast.popupDurationModified) {
			return false;
		}
		
		if (clickDestinationUrl == null ? _cast.clickDestinationUrl != clickDestinationUrl : !clickDestinationUrl.equals( _cast.clickDestinationUrl )) {
			return false;
		}
		
		if (clickDestinationUrlModified != _cast.clickDestinationUrlModified) {
			return false;
		}
		
		if (destination == null ? _cast.destination != destination : !destination.equals( _cast.destination )) {
			return false;
		}
		
		if (destinationModified != _cast.destinationModified) {
			return false;
		}
		
		if (groupName == null ? _cast.groupName != groupName : !groupName.equals( _cast.groupName )) {
			return false;
		}
		
		if (groupNameModified != _cast.groupNameModified) {
			return false;
		}
		
		if (viveId == null ? _cast.viveId != viveId : !viveId.equals( _cast.viveId )) {
			return false;
		}
		
		if (viveIdModified != _cast.viveIdModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (messageId ^ (messageId >>> 32));
		_hashCode = 29 * _hashCode + (messageIdModified ? 1 : 0);
		if (type != null) {
			_hashCode = 29 * _hashCode + type.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (typeModified ? 1 : 0);
		if (startTime != null) {
			_hashCode = 29 * _hashCode + startTime.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (startTimeModified ? 1 : 0);
		if (endTime != null) {
			_hashCode = 29 * _hashCode + endTime.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (endTimeModified ? 1 : 0);
		if (modTime != null) {
			_hashCode = 29 * _hashCode + modTime.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (modTimeModified ? 1 : 0);
		if (title != null) {
			_hashCode = 29 * _hashCode + title.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (titleModified ? 1 : 0);
		if (contents != null) {
			_hashCode = 29 * _hashCode + contents.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contentsModified ? 1 : 0);
		if (summary != null) {
			_hashCode = 29 * _hashCode + summary.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (summaryModified ? 1 : 0);
		if (priority != null) {
			_hashCode = 29 * _hashCode + priority.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (priorityModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) (popupDuration ^ (popupDuration >>> 32));
		_hashCode = 29 * _hashCode + (popupDurationModified ? 1 : 0);
		if (clickDestinationUrl != null) {
			_hashCode = 29 * _hashCode + clickDestinationUrl.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (clickDestinationUrlModified ? 1 : 0);
		if (destination != null) {
			_hashCode = 29 * _hashCode + destination.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (destinationModified ? 1 : 0);
		if (groupName != null) {
			_hashCode = 29 * _hashCode + groupName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (groupNameModified ? 1 : 0);
		if (viveId != null) {
			_hashCode = 29 * _hashCode + viveId.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (viveIdModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MessagesPk
	 */
	public MessagesPk createPk()
	{
		return new MessagesPk(messageId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nhcsys.dataaccess.dto.Messages: " );
		ret.append( "messageId=" + messageId );
		ret.append( ", type=" + type );
		ret.append( ", startTime=" + startTime );
		ret.append( ", endTime=" + endTime );
		ret.append( ", modTime=" + modTime );
		ret.append( ", title=" + title );
		ret.append( ", contents=" + contents );
		ret.append( ", summary=" + summary );
		ret.append( ", priority=" + priority );
		ret.append( ", popupDuration=" + popupDuration );
		ret.append( ", clickDestinationUrl=" + clickDestinationUrl );
		ret.append( ", destination=" + destination );
		ret.append( ", groupName=" + groupName );
		ret.append( ", viveId=" + viveId );
		return ret.toString();
	}

}
