/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.nhcsys.dataaccess.dao.ClqinfoDao;
import com.nhcsys.dataaccess.dto.Clqinfo;
import com.nhcsys.dataaccess.exceptions.ClqinfoDaoException;
import com.nhcsys.dataaccess.factory.ClqinfoDaoFactory;

public class ClqinfoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereClqinfoIdEquals(0);
		// findWhereNetworkinfoIdEquals(0);
		// findWhereNameEquals("");
		// findWhereCmdlineEquals("");
		// findWhereResultEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ClqinfoDao _dao = getClqinfoDao();
			Clqinfo _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereClqinfoIdEquals'
	 * 
	 * @param clqinfoId
	 */
	public static void findWhereClqinfoIdEquals(long clqinfoId)
	{
		try {
			ClqinfoDao _dao = getClqinfoDao();
			Clqinfo _result[] = _dao.findWhereClqinfoIdEquals(clqinfoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNetworkinfoIdEquals'
	 * 
	 * @param networkinfoId
	 */
	public static void findWhereNetworkinfoIdEquals(long networkinfoId)
	{
		try {
			ClqinfoDao _dao = getClqinfoDao();
			Clqinfo _result[] = _dao.findWhereNetworkinfoIdEquals(networkinfoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 */
	public static void findWhereNameEquals(String name)
	{
		try {
			ClqinfoDao _dao = getClqinfoDao();
			Clqinfo _result[] = _dao.findWhereNameEquals(name);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCmdlineEquals'
	 * 
	 * @param cmdline
	 */
	public static void findWhereCmdlineEquals(String cmdline)
	{
		try {
			ClqinfoDao _dao = getClqinfoDao();
			Clqinfo _result[] = _dao.findWhereCmdlineEquals(cmdline);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereResultEquals'
	 * 
	 * @param result
	 */
	public static void findWhereResultEquals(String result)
	{
		try {
			ClqinfoDao _dao = getClqinfoDao();
			Clqinfo _result[] = _dao.findWhereResultEquals(result);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getClqinfoDao'
	 * 
	 * @return ClqinfoDao
	 */
	public static ClqinfoDao getClqinfoDao()
	{
		return ClqinfoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Clqinfo dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getClqinfoId() );
		buf.append( ", " );
		buf.append( dto.getNetworkinfoId() );
		buf.append( ", " );
		buf.append( dto.getName() );
		buf.append( ", " );
		buf.append( dto.getCmdline() );
		buf.append( ", " );
		buf.append( dto.getResult() );
		System.out.println( buf.toString() );
	}

}
