/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.nhcsys.dataaccess.dao.SnmpqinfoDao;
import com.nhcsys.dataaccess.dto.Snmpqinfo;
import com.nhcsys.dataaccess.exceptions.SnmpqinfoDaoException;
import com.nhcsys.dataaccess.factory.SnmpqinfoDaoFactory;

public class SnmpqinfoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereSnmpqinfoIdEquals(0);
		// findWhereNetworkinfoIdEquals(0);
		// findWhereNameEquals("");
		// findWhereTreeEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			SnmpqinfoDao _dao = getSnmpqinfoDao();
			Snmpqinfo _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSnmpqinfoIdEquals'
	 * 
	 * @param snmpqinfoId
	 */
	public static void findWhereSnmpqinfoIdEquals(long snmpqinfoId)
	{
		try {
			SnmpqinfoDao _dao = getSnmpqinfoDao();
			Snmpqinfo _result[] = _dao.findWhereSnmpqinfoIdEquals(snmpqinfoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNetworkinfoIdEquals'
	 * 
	 * @param networkinfoId
	 */
	public static void findWhereNetworkinfoIdEquals(long networkinfoId)
	{
		try {
			SnmpqinfoDao _dao = getSnmpqinfoDao();
			Snmpqinfo _result[] = _dao.findWhereNetworkinfoIdEquals(networkinfoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 */
	public static void findWhereNameEquals(String name)
	{
		try {
			SnmpqinfoDao _dao = getSnmpqinfoDao();
			Snmpqinfo _result[] = _dao.findWhereNameEquals(name);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTreeEquals'
	 * 
	 * @param tree
	 */
	public static void findWhereTreeEquals(String tree)
	{
		try {
			SnmpqinfoDao _dao = getSnmpqinfoDao();
			Snmpqinfo _result[] = _dao.findWhereTreeEquals(tree);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getSnmpqinfoDao'
	 * 
	 * @return SnmpqinfoDao
	 */
	public static SnmpqinfoDao getSnmpqinfoDao()
	{
		return SnmpqinfoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Snmpqinfo dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getSnmpqinfoId() );
		buf.append( ", " );
		buf.append( dto.getNetworkinfoId() );
		buf.append( ", " );
		buf.append( dto.getName() );
		buf.append( ", " );
		buf.append( dto.getTree() );
		System.out.println( buf.toString() );
	}

}
