/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.nhcsys.dataaccess.dao.TelesalesOrgsDao;
import com.nhcsys.dataaccess.dto.TelesalesOrgs;
import com.nhcsys.dataaccess.exceptions.TelesalesOrgsDaoException;
import com.nhcsys.dataaccess.factory.TelesalesOrgsDaoFactory;

public class TelesalesOrgsDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereOrgIdEquals(0);
		// findWhereOrgNameEquals("");
		// findWhereConfigValueEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			TelesalesOrgsDao _dao = getTelesalesOrgsDao();
			TelesalesOrgs _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrgIdEquals'
	 * 
	 * @param orgId
	 */
	public static void findWhereOrgIdEquals(long orgId)
	{
		try {
			TelesalesOrgsDao _dao = getTelesalesOrgsDao();
			TelesalesOrgs _result[] = _dao.findWhereOrgIdEquals(orgId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrgNameEquals'
	 * 
	 * @param orgName
	 */
	public static void findWhereOrgNameEquals(String orgName)
	{
		try {
			TelesalesOrgsDao _dao = getTelesalesOrgsDao();
			TelesalesOrgs _result[] = _dao.findWhereOrgNameEquals(orgName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereConfigValueEquals'
	 * 
	 * @param configValue
	 */
	public static void findWhereConfigValueEquals(String configValue)
	{
		try {
			TelesalesOrgsDao _dao = getTelesalesOrgsDao();
			TelesalesOrgs _result[] = _dao.findWhereConfigValueEquals(configValue);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getTelesalesOrgsDao'
	 * 
	 * @return TelesalesOrgsDao
	 */
	public static TelesalesOrgsDao getTelesalesOrgsDao()
	{
		return TelesalesOrgsDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(TelesalesOrgs dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getOrgId() );
		buf.append( ", " );
		buf.append( dto.getOrgName() );
		buf.append( ", " );
		buf.append( dto.getConfigValue() );
		System.out.println( buf.toString() );
	}

}
