/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.j2ee.delegate;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import com.nhcsys.dataaccess.j2ee.session.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;
import org.apache.log4j.Logger;

public class TelesalesCallSourceDelegate implements TelesalesCallSourceDao
{
	private TelesalesCallSourceSession session;

	protected static final Logger logger = Logger.getLogger( TelesalesCallSourceDelegate.class );

	private int maxRows;

	/**
	 * Method 'TelesalesCallSourceDelegate'
	 * 
	 * @param session
	 */
	public TelesalesCallSourceDelegate(final TelesalesCallSourceSession session)
	{
		this.session = session;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/** 
	 * Inserts a new row in the TELESALES_CALL_SOURCE table.
	 */
	public TelesalesCallSourcePk insert(TelesalesCallSource dto) throws TelesalesCallSourceDaoException
	{
		try {
			return session.insert(dto);
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the TELESALES_CALL_SOURCE table.
	 */
	public void update(TelesalesCallSourcePk pk, TelesalesCallSource dto) throws TelesalesCallSourceDaoException
	{
		try {
			session.update(pk, dto);
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the TELESALES_CALL_SOURCE table.
	 */
	public void delete(TelesalesCallSourcePk pk) throws TelesalesCallSourceDaoException
	{
		try {
			session.delete(pk);
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param pk
	 * @throws TelesalesCallSourceDaoException
	 * @return TelesalesCallSource
	 */
	public TelesalesCallSource findByPrimaryKey(TelesalesCallSourcePk pk) throws TelesalesCallSourceDaoException
	{
		try {
			return session.findByPrimaryKey(pk);
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param sourceId
	 * @throws TelesalesCallSourceDaoException
	 * @return TelesalesCallSource
	 */
	public TelesalesCallSource findByPrimaryKey(long sourceId) throws TelesalesCallSourceDaoException
	{
		try {
			return session.findByPrimaryKey(sourceId);
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws TelesalesCallSourceDaoException
	 * @return TelesalesCallSource[]
	 */
	public TelesalesCallSource[] findAll() throws TelesalesCallSourceDaoException
	{
		try {
			return session.findAll();
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereSourceIdEquals'
	 * 
	 * @param sourceId
	 * @throws TelesalesCallSourceDaoException
	 * @return TelesalesCallSource[]
	 */
	public TelesalesCallSource[] findWhereSourceIdEquals(long sourceId) throws TelesalesCallSourceDaoException
	{
		try {
			return session.findWhereSourceIdEquals(sourceId);
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereSourceDescEquals'
	 * 
	 * @param sourceDesc
	 * @throws TelesalesCallSourceDaoException
	 * @return TelesalesCallSource[]
	 */
	public TelesalesCallSource[] findWhereSourceDescEquals(String sourceDesc) throws TelesalesCallSourceDaoException
	{
		try {
			return session.findWhereSourceDescEquals(sourceDesc);
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param sqlParams
	 * @throws TelesalesCallSourceDaoException
	 * @return TelesalesCallSource[]
	 */
	public TelesalesCallSource[] findByDynamicSelect(String sql, Object[] sqlParams) throws TelesalesCallSourceDaoException
	{
		try {
			return session.findByDynamicSelect(sql, sqlParams);
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param sqlParams
	 * @throws TelesalesCallSourceDaoException
	 * @return TelesalesCallSource[]
	 */
	public TelesalesCallSource[] findByDynamicWhere(String sql, Object[] sqlParams) throws TelesalesCallSourceDaoException
	{
		try {
			return session.findByDynamicWhere(sql, sqlParams);
		}
		catch (TelesalesCallSourceDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new TelesalesCallSourceDaoException( ex.getMessage() );
		}
		
	}

}
