/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.j2ee.delegate;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import com.nhcsys.dataaccess.j2ee.session.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;
import org.apache.log4j.Logger;

public class WmiqinfoDelegate implements WmiqinfoDao
{
	private WmiqinfoSession session;

	protected static final Logger logger = Logger.getLogger( WmiqinfoDelegate.class );

	private int maxRows;

	/**
	 * Method 'WmiqinfoDelegate'
	 * 
	 * @param session
	 */
	public WmiqinfoDelegate(final WmiqinfoSession session)
	{
		this.session = session;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/** 
	 * Inserts a new row in the WMIQINFO table.
	 */
	public WmiqinfoPk insert(Wmiqinfo dto) throws WmiqinfoDaoException
	{
		try {
			return session.insert(dto);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the WMIQINFO table.
	 */
	public void update(WmiqinfoPk pk, Wmiqinfo dto) throws WmiqinfoDaoException
	{
		try {
			session.update(pk, dto);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the WMIQINFO table.
	 */
	public void delete(WmiqinfoPk pk) throws WmiqinfoDaoException
	{
		try {
			session.delete(pk);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param pk
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo
	 */
	public Wmiqinfo findByPrimaryKey(WmiqinfoPk pk) throws WmiqinfoDaoException
	{
		try {
			return session.findByPrimaryKey(pk);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param wmiqinfoId
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo
	 */
	public Wmiqinfo findByPrimaryKey(long wmiqinfoId) throws WmiqinfoDaoException
	{
		try {
			return session.findByPrimaryKey(wmiqinfoId);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo[]
	 */
	public Wmiqinfo[] findAll() throws WmiqinfoDaoException
	{
		try {
			return session.findAll();
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereWmiqinfoIdEquals'
	 * 
	 * @param wmiqinfoId
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo[]
	 */
	public Wmiqinfo[] findWhereWmiqinfoIdEquals(long wmiqinfoId) throws WmiqinfoDaoException
	{
		try {
			return session.findWhereWmiqinfoIdEquals(wmiqinfoId);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereNetworkinfoIdEquals'
	 * 
	 * @param networkinfoId
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo[]
	 */
	public Wmiqinfo[] findWhereNetworkinfoIdEquals(long networkinfoId) throws WmiqinfoDaoException
	{
		try {
			return session.findWhereNetworkinfoIdEquals(networkinfoId);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo[]
	 */
	public Wmiqinfo[] findWhereNameEquals(String name) throws WmiqinfoDaoException
	{
		try {
			return session.findWhereNameEquals(name);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereQueryEquals'
	 * 
	 * @param query
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo[]
	 */
	public Wmiqinfo[] findWhereQueryEquals(String query) throws WmiqinfoDaoException
	{
		try {
			return session.findWhereQueryEquals(query);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereResultEquals'
	 * 
	 * @param result
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo[]
	 */
	public Wmiqinfo[] findWhereResultEquals(String result) throws WmiqinfoDaoException
	{
		try {
			return session.findWhereResultEquals(result);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param sqlParams
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo[]
	 */
	public Wmiqinfo[] findByDynamicSelect(String sql, Object[] sqlParams) throws WmiqinfoDaoException
	{
		try {
			return session.findByDynamicSelect(sql, sqlParams);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param sqlParams
	 * @throws WmiqinfoDaoException
	 * @return Wmiqinfo[]
	 */
	public Wmiqinfo[] findByDynamicWhere(String sql, Object[] sqlParams) throws WmiqinfoDaoException
	{
		try {
			return session.findByDynamicWhere(sql, sqlParams);
		}
		catch (WmiqinfoDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new WmiqinfoDaoException( ex.getMessage() );
		}
		
	}

}
