/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.j2ee.delegate;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import com.nhcsys.dataaccess.j2ee.session.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;
import org.apache.log4j.Logger;

public class ServerRuntimeConfigDelegate implements ServerRuntimeConfigDao
{
	private ServerRuntimeConfigSession session;

	protected static final Logger logger = Logger.getLogger( ServerRuntimeConfigDelegate.class );

	private int maxRows;

	/**
	 * Method 'ServerRuntimeConfigDelegate'
	 * 
	 * @param session
	 */
	public ServerRuntimeConfigDelegate(final ServerRuntimeConfigSession session)
	{
		this.session = session;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/** 
	 * Inserts a new row in the SERVER_RUNTIME_CONFIG table.
	 */
	public ServerRuntimeConfigPk insert(ServerRuntimeConfig dto) throws ServerRuntimeConfigDaoException
	{
		try {
			return session.insert(dto);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the SERVER_RUNTIME_CONFIG table.
	 */
	public void update(ServerRuntimeConfigPk pk, ServerRuntimeConfig dto) throws ServerRuntimeConfigDaoException
	{
		try {
			session.update(pk, dto);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the SERVER_RUNTIME_CONFIG table.
	 */
	public void delete(ServerRuntimeConfigPk pk) throws ServerRuntimeConfigDaoException
	{
		try {
			session.delete(pk);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param pk
	 * @throws ServerRuntimeConfigDaoException
	 * @return ServerRuntimeConfig
	 */
	public ServerRuntimeConfig findByPrimaryKey(ServerRuntimeConfigPk pk) throws ServerRuntimeConfigDaoException
	{
		try {
			return session.findByPrimaryKey(pk);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param configKey
	 * @throws ServerRuntimeConfigDaoException
	 * @return ServerRuntimeConfig
	 */
	public ServerRuntimeConfig findByPrimaryKey(String configKey) throws ServerRuntimeConfigDaoException
	{
		try {
			return session.findByPrimaryKey(configKey);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws ServerRuntimeConfigDaoException
	 * @return ServerRuntimeConfig[]
	 */
	public ServerRuntimeConfig[] findAll() throws ServerRuntimeConfigDaoException
	{
		try {
			return session.findAll();
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereConfigIdEquals'
	 * 
	 * @param configId
	 * @throws ServerRuntimeConfigDaoException
	 * @return ServerRuntimeConfig[]
	 */
	public ServerRuntimeConfig[] findWhereConfigIdEquals(long configId) throws ServerRuntimeConfigDaoException
	{
		try {
			return session.findWhereConfigIdEquals(configId);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereConfigKeyEquals'
	 * 
	 * @param configKey
	 * @throws ServerRuntimeConfigDaoException
	 * @return ServerRuntimeConfig[]
	 */
	public ServerRuntimeConfig[] findWhereConfigKeyEquals(String configKey) throws ServerRuntimeConfigDaoException
	{
		try {
			return session.findWhereConfigKeyEquals(configKey);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereConfigValueEquals'
	 * 
	 * @param configValue
	 * @throws ServerRuntimeConfigDaoException
	 * @return ServerRuntimeConfig[]
	 */
	public ServerRuntimeConfig[] findWhereConfigValueEquals(String configValue) throws ServerRuntimeConfigDaoException
	{
		try {
			return session.findWhereConfigValueEquals(configValue);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param sqlParams
	 * @throws ServerRuntimeConfigDaoException
	 * @return ServerRuntimeConfig[]
	 */
	public ServerRuntimeConfig[] findByDynamicSelect(String sql, Object[] sqlParams) throws ServerRuntimeConfigDaoException
	{
		try {
			return session.findByDynamicSelect(sql, sqlParams);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param sqlParams
	 * @throws ServerRuntimeConfigDaoException
	 * @return ServerRuntimeConfig[]
	 */
	public ServerRuntimeConfig[] findByDynamicWhere(String sql, Object[] sqlParams) throws ServerRuntimeConfigDaoException
	{
		try {
			return session.findByDynamicWhere(sql, sqlParams);
		}
		catch (ServerRuntimeConfigDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			logger.error( ex);
			throw new ServerRuntimeConfigDaoException( ex.getMessage() );
		}
		
	}

}
