/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.nhcsys.dataaccess.dao.InstalledSoftwareDao;
import com.nhcsys.dataaccess.dto.InstalledSoftware;
import com.nhcsys.dataaccess.exceptions.InstalledSoftwareDaoException;
import com.nhcsys.dataaccess.factory.InstalledSoftwareDaoFactory;

public class InstalledSoftwareDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findWhereSessionIdEquals("");
		// findAll();
		// findWhereSoftwareIdEquals(0);
		// findWhereCustomerIdEquals(0);
		// findWhereMachineIdEquals(0);
		// findWhereProductKeyEquals("");
		// findWhereProductNameEquals("");
		// findWhereCompanyNameEquals("");
		// findWhereProductVersionEquals("");
	}

	/**
	 * Method 'findWhereSessionIdEquals'
	 * 
	 * @param sessionId
	 */
	public static void findWhereSessionIdEquals(String sessionId)
	{
		try {
			InstalledSoftwareDao _dao = getInstalledSoftwareDao();
			InstalledSoftware _result[] = _dao.findWhereSessionIdEquals(sessionId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			InstalledSoftwareDao _dao = getInstalledSoftwareDao();
			InstalledSoftware _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSoftwareIdEquals'
	 * 
	 * @param softwareId
	 */
	public static void findWhereSoftwareIdEquals(long softwareId)
	{
		try {
			InstalledSoftwareDao _dao = getInstalledSoftwareDao();
			InstalledSoftware _result[] = _dao.findWhereSoftwareIdEquals(softwareId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCustomerIdEquals'
	 * 
	 * @param customerId
	 */
	public static void findWhereCustomerIdEquals(long customerId)
	{
		try {
			InstalledSoftwareDao _dao = getInstalledSoftwareDao();
			InstalledSoftware _result[] = _dao.findWhereCustomerIdEquals(customerId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMachineIdEquals'
	 * 
	 * @param machineId
	 */
	public static void findWhereMachineIdEquals(long machineId)
	{
		try {
			InstalledSoftwareDao _dao = getInstalledSoftwareDao();
			InstalledSoftware _result[] = _dao.findWhereMachineIdEquals(machineId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductKeyEquals'
	 * 
	 * @param productKey
	 */
	public static void findWhereProductKeyEquals(String productKey)
	{
		try {
			InstalledSoftwareDao _dao = getInstalledSoftwareDao();
			InstalledSoftware _result[] = _dao.findWhereProductKeyEquals(productKey);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductNameEquals'
	 * 
	 * @param productName
	 */
	public static void findWhereProductNameEquals(String productName)
	{
		try {
			InstalledSoftwareDao _dao = getInstalledSoftwareDao();
			InstalledSoftware _result[] = _dao.findWhereProductNameEquals(productName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCompanyNameEquals'
	 * 
	 * @param companyName
	 */
	public static void findWhereCompanyNameEquals(String companyName)
	{
		try {
			InstalledSoftwareDao _dao = getInstalledSoftwareDao();
			InstalledSoftware _result[] = _dao.findWhereCompanyNameEquals(companyName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductVersionEquals'
	 * 
	 * @param productVersion
	 */
	public static void findWhereProductVersionEquals(String productVersion)
	{
		try {
			InstalledSoftwareDao _dao = getInstalledSoftwareDao();
			InstalledSoftware _result[] = _dao.findWhereProductVersionEquals(productVersion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getInstalledSoftwareDao'
	 * 
	 * @return InstalledSoftwareDao
	 */
	public static InstalledSoftwareDao getInstalledSoftwareDao()
	{
		return InstalledSoftwareDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(InstalledSoftware dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getSoftwareId() );
		buf.append( ", " );
		buf.append( dto.getMachineId() );
		buf.append( ", " );
		buf.append( dto.getProductKey() );
		buf.append( ", " );
		buf.append( dto.getProductName() );
		buf.append( ", " );
		buf.append( dto.getCompanyName() );
		buf.append( ", " );
		buf.append( dto.getProductVersion() );
		buf.append( ", " );
		buf.append( dto.getCustomerId() );
		System.out.println( buf.toString() );
	}

}
