/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.nhcsys.dataaccess.dao.TelesalesRepsDao;
import com.nhcsys.dataaccess.dto.TelesalesReps;
import com.nhcsys.dataaccess.exceptions.TelesalesRepsDaoException;
import com.nhcsys.dataaccess.factory.TelesalesRepsDaoFactory;

public class TelesalesRepsDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByTelesalesOrgs(0);
		// findWhereRepIdEquals(0);
		// findWhereOrgIdEquals(0);
		// findWhereUserIdEquals("");
		// findWherePasswordTextEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			TelesalesRepsDao _dao = getTelesalesRepsDao();
			TelesalesReps _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByTelesalesOrgs'
	 * 
	 * @param orgId
	 */
	public static void findByTelesalesOrgs(long orgId)
	{
		try {
			TelesalesRepsDao _dao = getTelesalesRepsDao();
			TelesalesReps _result[] = _dao.findByTelesalesOrgs(orgId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRepIdEquals'
	 * 
	 * @param repId
	 */
	public static void findWhereRepIdEquals(long repId)
	{
		try {
			TelesalesRepsDao _dao = getTelesalesRepsDao();
			TelesalesReps _result[] = _dao.findWhereRepIdEquals(repId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrgIdEquals'
	 * 
	 * @param orgId
	 */
	public static void findWhereOrgIdEquals(long orgId)
	{
		try {
			TelesalesRepsDao _dao = getTelesalesRepsDao();
			TelesalesReps _result[] = _dao.findWhereOrgIdEquals(orgId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUserIdEquals'
	 * 
	 * @param userId
	 */
	public static void findWhereUserIdEquals(String userId)
	{
		try {
			TelesalesRepsDao _dao = getTelesalesRepsDao();
			TelesalesReps _result[] = _dao.findWhereUserIdEquals(userId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePasswordTextEquals'
	 * 
	 * @param passwordText
	 */
	public static void findWherePasswordTextEquals(String passwordText)
	{
		try {
			TelesalesRepsDao _dao = getTelesalesRepsDao();
			TelesalesReps _result[] = _dao.findWherePasswordTextEquals(passwordText);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getTelesalesRepsDao'
	 * 
	 * @return TelesalesRepsDao
	 */
	public static TelesalesRepsDao getTelesalesRepsDao()
	{
		return TelesalesRepsDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(TelesalesReps dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getRepId() );
		buf.append( ", " );
		buf.append( dto.getOrgId() );
		buf.append( ", " );
		buf.append( dto.getUserId() );
		buf.append( ", " );
		buf.append( dto.getPasswordText() );
		System.out.println( buf.toString() );
	}

}
