/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.nhcsys.dataaccess.dao.WmiqinfoDao;
import com.nhcsys.dataaccess.dto.Wmiqinfo;
import com.nhcsys.dataaccess.exceptions.WmiqinfoDaoException;
import com.nhcsys.dataaccess.factory.WmiqinfoDaoFactory;

public class WmiqinfoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereWmiqinfoIdEquals(0);
		// findWhereNetworkinfoIdEquals(0);
		// findWhereNameEquals("");
		// findWhereQueryEquals("");
		// findWhereResultEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			WmiqinfoDao _dao = getWmiqinfoDao();
			Wmiqinfo _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereWmiqinfoIdEquals'
	 * 
	 * @param wmiqinfoId
	 */
	public static void findWhereWmiqinfoIdEquals(long wmiqinfoId)
	{
		try {
			WmiqinfoDao _dao = getWmiqinfoDao();
			Wmiqinfo _result[] = _dao.findWhereWmiqinfoIdEquals(wmiqinfoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNetworkinfoIdEquals'
	 * 
	 * @param networkinfoId
	 */
	public static void findWhereNetworkinfoIdEquals(long networkinfoId)
	{
		try {
			WmiqinfoDao _dao = getWmiqinfoDao();
			Wmiqinfo _result[] = _dao.findWhereNetworkinfoIdEquals(networkinfoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 */
	public static void findWhereNameEquals(String name)
	{
		try {
			WmiqinfoDao _dao = getWmiqinfoDao();
			Wmiqinfo _result[] = _dao.findWhereNameEquals(name);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereQueryEquals'
	 * 
	 * @param query
	 */
	public static void findWhereQueryEquals(String query)
	{
		try {
			WmiqinfoDao _dao = getWmiqinfoDao();
			Wmiqinfo _result[] = _dao.findWhereQueryEquals(query);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereResultEquals'
	 * 
	 * @param result
	 */
	public static void findWhereResultEquals(String result)
	{
		try {
			WmiqinfoDao _dao = getWmiqinfoDao();
			Wmiqinfo _result[] = _dao.findWhereResultEquals(result);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getWmiqinfoDao'
	 * 
	 * @return WmiqinfoDao
	 */
	public static WmiqinfoDao getWmiqinfoDao()
	{
		return WmiqinfoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Wmiqinfo dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getWmiqinfoId() );
		buf.append( ", " );
		buf.append( dto.getNetworkinfoId() );
		buf.append( ", " );
		buf.append( dto.getName() );
		buf.append( ", " );
		buf.append( dto.getQuery() );
		buf.append( ", " );
		buf.append( dto.getResult() );
		System.out.println( buf.toString() );
	}

}
