/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.dao;

import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;

public interface ServerRuntimeConfigDao
{
	/** 
	 * Inserts a new row in the SERVER_RUNTIME_CONFIG table.
	 */
	public ServerRuntimeConfigPk insert(ServerRuntimeConfig dto) throws ServerRuntimeConfigDaoException;

	/** 
	 * Updates a single row in the SERVER_RUNTIME_CONFIG table.
	 */
	public void update(ServerRuntimeConfigPk pk, ServerRuntimeConfig dto) throws ServerRuntimeConfigDaoException;

	/** 
	 * Deletes a single row in the SERVER_RUNTIME_CONFIG table.
	 */
	public void delete(ServerRuntimeConfigPk pk) throws ServerRuntimeConfigDaoException;

	/** 
	 * Returns the rows from the SERVER_RUNTIME_CONFIG table that matches the specified primary-key value.
	 */
	public ServerRuntimeConfig findByPrimaryKey(ServerRuntimeConfigPk pk) throws ServerRuntimeConfigDaoException;

	/** 
	 * Returns all rows from the SERVER_RUNTIME_CONFIG table that match the criteria 'CONFIG_KEY = :configKey'.
	 */
	public ServerRuntimeConfig findByPrimaryKey(String configKey) throws ServerRuntimeConfigDaoException;

	/** 
	 * Returns all rows from the SERVER_RUNTIME_CONFIG table that match the criteria ''.
	 */
	public ServerRuntimeConfig[] findAll() throws ServerRuntimeConfigDaoException;

	/** 
	 * Returns all rows from the SERVER_RUNTIME_CONFIG table that match the criteria 'CONFIG_ID = :configId'.
	 */
	public ServerRuntimeConfig[] findWhereConfigIdEquals(long configId) throws ServerRuntimeConfigDaoException;

	/** 
	 * Returns all rows from the SERVER_RUNTIME_CONFIG table that match the criteria 'CONFIG_KEY = :configKey'.
	 */
	public ServerRuntimeConfig[] findWhereConfigKeyEquals(String configKey) throws ServerRuntimeConfigDaoException;

	/** 
	 * Returns all rows from the SERVER_RUNTIME_CONFIG table that match the criteria 'CONFIG_VALUE = :configValue'.
	 */
	public ServerRuntimeConfig[] findWhereConfigValueEquals(String configValue) throws ServerRuntimeConfigDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the SERVER_RUNTIME_CONFIG table that match the specified arbitrary SQL statement
	 */
	public ServerRuntimeConfig[] findByDynamicSelect(String sql, Object[] sqlParams) throws ServerRuntimeConfigDaoException;

	/** 
	 * Returns all rows from the SERVER_RUNTIME_CONFIG table that match the specified arbitrary SQL statement
	 */
	public ServerRuntimeConfig[] findByDynamicWhere(String sql, Object[] sqlParams) throws ServerRuntimeConfigDaoException;

}
