/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.j2ee.session;

import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;

public interface MachinesSession extends EJBObject
{
	/** 
	 * Inserts a new row in the MACHINES table.
	 */
	public MachinesPk insert(Machines dto) throws MachinesDaoException, RemoteException;

	/** 
	 * Updates a single row in the MACHINES table.
	 */
	public void update(MachinesPk pk, Machines dto) throws MachinesDaoException, RemoteException;

	/** 
	 * Deletes a single row in the MACHINES table.
	 */
	public void delete(MachinesPk pk) throws MachinesDaoException, RemoteException;

	/** 
	 * Returns the rows from the MACHINES table that matches the specified primary-key value.
	 */
	public Machines findByPrimaryKey(MachinesPk pk) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param machineId
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines
	 */
	public Machines findByPrimaryKey(long machineId) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findAll'
	 * 
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findAll() throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findWhereMachineIdEquals'
	 * 
	 * @param machineId
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findWhereMachineIdEquals(long machineId) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findWhereCustomerIdEquals'
	 * 
	 * @param customerId
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findWhereCustomerIdEquals(long customerId) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findWhereViveIdEquals'
	 * 
	 * @param viveId
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findWhereViveIdEquals(String viveId) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findWhereCpuSerialNoEquals'
	 * 
	 * @param cpuSerialNo
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findWhereCpuSerialNoEquals(String cpuSerialNo) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findWhereKeyDataEquals'
	 * 
	 * @param keyData
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findWhereKeyDataEquals(String keyData) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findWhereKeyTimestampEquals'
	 * 
	 * @param keyTimestamp
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findWhereKeyTimestampEquals(long keyTimestamp) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findWhereStolenFlagEquals'
	 * 
	 * @param stolenFlag
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findWhereStolenFlagEquals(int stolenFlag) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findWhereTerminateFlagEquals'
	 * 
	 * @param terminateFlag
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findWhereTerminateFlagEquals(int terminateFlag) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findWhereRegisteredFlagEquals'
	 * 
	 * @param registeredFlag
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findWhereRegisteredFlagEquals(int registeredFlag) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param arg
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findByDynamicSelect(String sql, Object[] arg) throws MachinesDaoException, RemoteException;

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param arg
	 * @throws MachinesDaoException
	 * @throws RemoteException
	 * @return Machines[]
	 */
	public Machines[] findByDynamicWhere(String sql, Object[] arg) throws MachinesDaoException, RemoteException;

}
