/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.factory;

import java.sql.Connection;
import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.jdbc.*;

public class WmiqinfoDaoFactory
{
	private static final WmiqinfoDaoImpl dao = new WmiqinfoDaoImpl();

	/**
	 * Method 'create'
	 * 
	 * @return WmiqinfoDao
	 */
	public static WmiqinfoDao create()
	{
		return dao;
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return WmiqinfoDao
	 */
	public static WmiqinfoDao create(Connection conn)
	{
		return new WmiqinfoDaoImpl( conn );
	}

}
