/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.jdbc;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class TelesalesCallSourceDaoImpl extends AbstractDAO implements TelesalesCallSourceDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( TelesalesCallSourceDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT SOURCE_ID, SOURCE_DESC FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	private int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( SOURCE_ID, SOURCE_DESC ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET SOURCE_ID = ?, SOURCE_DESC = ? WHERE SOURCE_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE SOURCE_ID = ?";

	/** 
	 * Index of column SOURCE_ID
	 */
	protected static final int COLUMN_SOURCE_ID = 1;

	/** 
	 * Index of column SOURCE_DESC
	 */
	protected static final int COLUMN_SOURCE_DESC = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column SOURCE_ID
	 */
	protected static final int PK_COLUMN_SOURCE_ID = 1;

	/** 
	 * Inserts a new row in the TELESALES_CALL_SOURCE table.
	 */
	public TelesalesCallSourcePk insert(TelesalesCallSource dto) throws TelesalesCallSourceDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( "SELECT source_id_seq.NEXTVAL FROM DUAL" );
			rs = stmt.executeQuery();
			if (rs.next()) {
				dto.setSourceId( rs.getLong( 1 ) );
				rs.close();
				stmt.close();
			}
		
			StringBuffer sql = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isSourceIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "SOURCE_ID" );
				modifiedCount++;
			}
		
			if (dto.isSourceDescModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "SOURCE_DESC" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			for (int i=0; i<modifiedCount; i++ ) {
				if (i>0) {
					sql.append( "," );
				}
		
				sql.append( "?" );
			}
		
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isSourceIdModified()) {
				stmt.setLong( index++, dto.getSourceId() );
			}
		
			if (dto.isSourceDescModified()) {
				stmt.setString( index++, dto.getSourceDesc() );
			}
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new TelesalesCallSourceDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the TELESALES_CALL_SOURCE table.
	 */
	public void update(TelesalesCallSourcePk pk, TelesalesCallSource dto) throws TelesalesCallSourceDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isSourceIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "SOURCE_ID=?" );
				modified=true;
			}
		
			if (dto.isSourceDescModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "SOURCE_DESC=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE SOURCE_ID=?" );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isSourceIdModified()) {
				stmt.setLong( index++, dto.getSourceId() );
			}
		
			if (dto.isSourceDescModified()) {
				stmt.setString( index++, dto.getSourceDesc() );
			}
		
			stmt.setLong( index++, pk.getSourceId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new TelesalesCallSourceDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the TELESALES_CALL_SOURCE table.
	 */
	public void delete(TelesalesCallSourcePk pk) throws TelesalesCallSourceDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getSourceId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new TelesalesCallSourceDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the TELESALES_CALL_SOURCE table that matches the specified primary-key value.
	 */
	public TelesalesCallSource findByPrimaryKey(TelesalesCallSourcePk pk) throws TelesalesCallSourceDaoException
	{
		return findByPrimaryKey( pk.getSourceId() );
	}

	/** 
	 * Returns all rows from the TELESALES_CALL_SOURCE table that match the criteria 'SOURCE_ID = :sourceId'.
	 */
	public TelesalesCallSource findByPrimaryKey(long sourceId) throws TelesalesCallSourceDaoException
	{
		TelesalesCallSource ret[] = findByDynamicSelect( SQL_SELECT + " WHERE SOURCE_ID = ?", new Object[] {  new Long(sourceId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the TELESALES_CALL_SOURCE table that match the criteria ''.
	 */
	public TelesalesCallSource[] findAll() throws TelesalesCallSourceDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY SOURCE_ID", null );
	}

	/** 
	 * Returns all rows from the TELESALES_CALL_SOURCE table that match the criteria 'SOURCE_ID = :sourceId'.
	 */
	public TelesalesCallSource[] findWhereSourceIdEquals(long sourceId) throws TelesalesCallSourceDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SOURCE_ID = ? ORDER BY SOURCE_ID", new Object[] {  new Long(sourceId) } );
	}

	/** 
	 * Returns all rows from the TELESALES_CALL_SOURCE table that match the criteria 'SOURCE_DESC = :sourceDesc'.
	 */
	public TelesalesCallSource[] findWhereSourceDescEquals(String sourceDesc) throws TelesalesCallSourceDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SOURCE_DESC = ? ORDER BY SOURCE_DESC", new Object[] { sourceDesc } );
	}

	/**
	 * Method 'TelesalesCallSourceDaoImpl'
	 * 
	 */
	public TelesalesCallSourceDaoImpl()
	{
	}

	/**
	 * Method 'TelesalesCallSourceDaoImpl'
	 * 
	 * @param userConn
	 */
	public TelesalesCallSourceDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "TELESALES_CALL_SOURCE";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected TelesalesCallSource fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			TelesalesCallSource dto = new TelesalesCallSource();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected TelesalesCallSource[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			TelesalesCallSource dto = new TelesalesCallSource();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		TelesalesCallSource ret[] = new TelesalesCallSource[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(TelesalesCallSource dto, ResultSet rs) throws SQLException
	{
		dto.setSourceId( rs.getLong( COLUMN_SOURCE_ID ) );
		dto.setSourceDesc( rs.getString( COLUMN_SOURCE_DESC ) );
	}

	/** 
	 * Returns all rows from the TELESALES_CALL_SOURCE table that match the specified arbitrary SQL statement
	 */
	public TelesalesCallSource[] findByDynamicSelect(String sql, Object[] sqlParams) throws TelesalesCallSourceDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new TelesalesCallSourceDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the TELESALES_CALL_SOURCE table that match the specified arbitrary SQL statement
	 */
	public TelesalesCallSource[] findByDynamicWhere(String sql, Object[] sqlParams) throws TelesalesCallSourceDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new TelesalesCallSourceDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
