/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.jdbc;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class UpdateStatusDaoImpl extends AbstractDAO implements UpdateStatusDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( UpdateStatusDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT UPDATE_STATUS_ID, SESSION_ID, MACHINE_ID, PRODUCT_ID, DESCRIPTION, REPORT, STATUS FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	private int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( UPDATE_STATUS_ID, SESSION_ID, MACHINE_ID, PRODUCT_ID, DESCRIPTION, REPORT, STATUS ) VALUES ( ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET UPDATE_STATUS_ID = ?, SESSION_ID = ?, MACHINE_ID = ?, PRODUCT_ID = ?, DESCRIPTION = ?, REPORT = ?, STATUS = ? WHERE UPDATE_STATUS_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE UPDATE_STATUS_ID = ?";

	/** 
	 * Index of column UPDATE_STATUS_ID
	 */
	protected static final int COLUMN_UPDATE_STATUS_ID = 1;

	/** 
	 * Index of column SESSION_ID
	 */
	protected static final int COLUMN_SESSION_ID = 2;

	/** 
	 * Index of column MACHINE_ID
	 */
	protected static final int COLUMN_MACHINE_ID = 3;

	/** 
	 * Index of column PRODUCT_ID
	 */
	protected static final int COLUMN_PRODUCT_ID = 4;

	/** 
	 * Index of column DESCRIPTION
	 */
	protected static final int COLUMN_DESCRIPTION = 5;

	/** 
	 * Index of column REPORT
	 */
	protected static final int COLUMN_REPORT = 6;

	/** 
	 * Index of column STATUS
	 */
	protected static final int COLUMN_STATUS = 7;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 7;

	/** 
	 * Index of primary-key column UPDATE_STATUS_ID
	 */
	protected static final int PK_COLUMN_UPDATE_STATUS_ID = 1;

	/** 
	 * Inserts a new row in the UPDATE_STATUS table.
	 */
	public UpdateStatusPk insert(UpdateStatus dto) throws UpdateStatusDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( "SELECT update_status_id_seq.NEXTVAL FROM DUAL" );
			rs = stmt.executeQuery();
			if (rs.next()) {
				dto.setUpdateStatusId( rs.getLong( 1 ) );
				rs.close();
				stmt.close();
			}
		
			StringBuffer sql = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isUpdateStatusIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "UPDATE_STATUS_ID" );
				modifiedCount++;
			}
		
			if (dto.isSessionIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "SESSION_ID" );
				modifiedCount++;
			}
		
			if (dto.isMachineIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "MACHINE_ID" );
				modifiedCount++;
			}
		
			if (dto.isProductIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "PRODUCT_ID" );
				modifiedCount++;
			}
		
			if (dto.isDescriptionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "DESCRIPTION" );
				modifiedCount++;
			}
		
			if (dto.isReportModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "REPORT" );
				modifiedCount++;
			}
		
			if (dto.isStatusModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "STATUS" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			for (int i=0; i<modifiedCount; i++ ) {
				if (i>0) {
					sql.append( "," );
				}
		
				sql.append( "?" );
			}
		
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isUpdateStatusIdModified()) {
				stmt.setLong( index++, dto.getUpdateStatusId() );
			}
		
			if (dto.isSessionIdModified()) {
				stmt.setString( index++, dto.getSessionId() );
			}
		
			if (dto.isMachineIdModified()) {
				stmt.setLong( index++, dto.getMachineId() );
			}
		
			if (dto.isProductIdModified()) {
				stmt.setString( index++, dto.getProductId() );
			}
		
			if (dto.isDescriptionModified()) {
				stmt.setString( index++, dto.getDescription() );
			}
		
			if (dto.isReportModified()) {
				stmt.setString( index++, dto.getReport() );
			}
		
			if (dto.isStatusModified()) {
				stmt.setString( index++, dto.getStatus() );
			}
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new UpdateStatusDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the UPDATE_STATUS table.
	 */
	public void update(UpdateStatusPk pk, UpdateStatus dto) throws UpdateStatusDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isUpdateStatusIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "UPDATE_STATUS_ID=?" );
				modified=true;
			}
		
			if (dto.isSessionIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "SESSION_ID=?" );
				modified=true;
			}
		
			if (dto.isMachineIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "MACHINE_ID=?" );
				modified=true;
			}
		
			if (dto.isProductIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "PRODUCT_ID=?" );
				modified=true;
			}
		
			if (dto.isDescriptionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "DESCRIPTION=?" );
				modified=true;
			}
		
			if (dto.isReportModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "REPORT=?" );
				modified=true;
			}
		
			if (dto.isStatusModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "STATUS=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE UPDATE_STATUS_ID=?" );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isUpdateStatusIdModified()) {
				stmt.setLong( index++, dto.getUpdateStatusId() );
			}
		
			if (dto.isSessionIdModified()) {
				stmt.setString( index++, dto.getSessionId() );
			}
		
			if (dto.isMachineIdModified()) {
				stmt.setLong( index++, dto.getMachineId() );
			}
		
			if (dto.isProductIdModified()) {
				stmt.setString( index++, dto.getProductId() );
			}
		
			if (dto.isDescriptionModified()) {
				stmt.setString( index++, dto.getDescription() );
			}
		
			if (dto.isReportModified()) {
				stmt.setString( index++, dto.getReport() );
			}
		
			if (dto.isStatusModified()) {
				stmt.setString( index++, dto.getStatus() );
			}
		
			stmt.setLong( index++, pk.getUpdateStatusId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new UpdateStatusDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the UPDATE_STATUS table.
	 */
	public void delete(UpdateStatusPk pk) throws UpdateStatusDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getUpdateStatusId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new UpdateStatusDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the UPDATE_STATUS table that matches the specified primary-key value.
	 */
	public UpdateStatus findByPrimaryKey(UpdateStatusPk pk) throws UpdateStatusDaoException
	{
		return findByPrimaryKey( pk.getUpdateStatusId() );
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the criteria 'UPDATE_STATUS_ID = :updateStatusId'.
	 */
	public UpdateStatus findByPrimaryKey(long updateStatusId) throws UpdateStatusDaoException
	{
		UpdateStatus ret[] = findByDynamicSelect( SQL_SELECT + " WHERE UPDATE_STATUS_ID = ?", new Object[] {  new Long(updateStatusId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the criteria ''.
	 */
	public UpdateStatus[] findAll() throws UpdateStatusDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY UPDATE_STATUS_ID", null );
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the criteria 'UPDATE_STATUS_ID = :updateStatusId'.
	 */
	public UpdateStatus[] findWhereUpdateStatusIdEquals(long updateStatusId) throws UpdateStatusDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE UPDATE_STATUS_ID = ? ORDER BY UPDATE_STATUS_ID", new Object[] {  new Long(updateStatusId) } );
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the criteria 'SESSION_ID = :sessionId'.
	 */
	public UpdateStatus[] findWhereSessionIdEquals(String sessionId) throws UpdateStatusDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SESSION_ID = ? ORDER BY SESSION_ID", new Object[] { sessionId } );
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the criteria 'MACHINE_ID = :machineId'.
	 */
	public UpdateStatus[] findWhereMachineIdEquals(long machineId) throws UpdateStatusDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MACHINE_ID = ? ORDER BY MACHINE_ID", new Object[] {  new Long(machineId) } );
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the criteria 'PRODUCT_ID = :productId'.
	 */
	public UpdateStatus[] findWhereProductIdEquals(String productId) throws UpdateStatusDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PRODUCT_ID = ? ORDER BY PRODUCT_ID", new Object[] { productId } );
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the criteria 'DESCRIPTION = :description'.
	 */
	public UpdateStatus[] findWhereDescriptionEquals(String description) throws UpdateStatusDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DESCRIPTION = ? ORDER BY DESCRIPTION", new Object[] { description } );
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the criteria 'REPORT = :report'.
	 */
	public UpdateStatus[] findWhereReportEquals(String report) throws UpdateStatusDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE REPORT = ? ORDER BY REPORT", new Object[] { report } );
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the criteria 'STATUS = :status'.
	 */
	public UpdateStatus[] findWhereStatusEquals(String status) throws UpdateStatusDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE STATUS = ? ORDER BY STATUS", new Object[] { status } );
	}

	/**
	 * Method 'UpdateStatusDaoImpl'
	 * 
	 */
	public UpdateStatusDaoImpl()
	{
	}

	/**
	 * Method 'UpdateStatusDaoImpl'
	 * 
	 * @param userConn
	 */
	public UpdateStatusDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "UPDATE_STATUS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected UpdateStatus fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			UpdateStatus dto = new UpdateStatus();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected UpdateStatus[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			UpdateStatus dto = new UpdateStatus();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		UpdateStatus ret[] = new UpdateStatus[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(UpdateStatus dto, ResultSet rs) throws SQLException
	{
		dto.setUpdateStatusId( rs.getLong( COLUMN_UPDATE_STATUS_ID ) );
		dto.setSessionId( rs.getString( COLUMN_SESSION_ID ) );
		dto.setMachineId( rs.getLong( COLUMN_MACHINE_ID ) );
		dto.setProductId( rs.getString( COLUMN_PRODUCT_ID ) );
		dto.setDescription( rs.getString( COLUMN_DESCRIPTION ) );
		dto.setReport( rs.getString( COLUMN_REPORT ) );
		dto.setStatus( rs.getString( COLUMN_STATUS ) );
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the specified arbitrary SQL statement
	 */
	public UpdateStatus[] findByDynamicSelect(String sql, Object[] sqlParams) throws UpdateStatusDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new UpdateStatusDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the UPDATE_STATUS table that match the specified arbitrary SQL statement
	 */
	public UpdateStatus[] findByDynamicWhere(String sql, Object[] sqlParams) throws UpdateStatusDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new UpdateStatusDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
