/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.dto;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Clqinfo implements Serializable
{
	/** 
	 * This attribute maps to the column CLQINFO_ID in the CLQINFO table.
	 */
	private long clqinfoId;

	/** 
	 * This attribute represents whether the attribute clqinfoId has been modified since being read from the database.
	 */
	private boolean clqinfoIdModified = false;

	/** 
	 * This attribute maps to the column NETWORKINFO_ID in the CLQINFO table.
	 */
	private long networkinfoId;

	/** 
	 * This attribute represents whether the attribute networkinfoId has been modified since being read from the database.
	 */
	private boolean networkinfoIdModified = false;

	/** 
	 * This attribute maps to the column NAME in the CLQINFO table.
	 */
	private String name;

	/** 
	 * This attribute represents whether the attribute name has been modified since being read from the database.
	 */
	private boolean nameModified = false;

	/** 
	 * This attribute maps to the column CMDLINE in the CLQINFO table.
	 */
	private String cmdline;

	/** 
	 * This attribute represents whether the attribute cmdline has been modified since being read from the database.
	 */
	private boolean cmdlineModified = false;

	/** 
	 * This attribute maps to the column RESULT in the CLQINFO table.
	 */
	private String result;

	/** 
	 * This attribute represents whether the attribute result has been modified since being read from the database.
	 */
	private boolean resultModified = false;

	/**
	 * Method 'Clqinfo'
	 * 
	 */
	public Clqinfo()
	{
	}

	/**
	 * Method 'getClqinfoId'
	 * 
	 * @return long
	 */
	public long getClqinfoId()
	{
		return clqinfoId;
	}

	/**
	 * Method 'setClqinfoId'
	 * 
	 * @param clqinfoId
	 */
	public void setClqinfoId(long clqinfoId)
	{
		this.clqinfoId = clqinfoId;
		setClqinfoIdModified( true );
	}

	/** 
	 * Sets the value of clqinfoIdModified
	 */
	public void setClqinfoIdModified(boolean clqinfoIdModified)
	{
		this.clqinfoIdModified = clqinfoIdModified;
	}

	/** 
	 * Gets the value of clqinfoIdModified
	 */
	public boolean isClqinfoIdModified()
	{
		return clqinfoIdModified;
	}

	/**
	 * Method 'getNetworkinfoId'
	 * 
	 * @return long
	 */
	public long getNetworkinfoId()
	{
		return networkinfoId;
	}

	/**
	 * Method 'setNetworkinfoId'
	 * 
	 * @param networkinfoId
	 */
	public void setNetworkinfoId(long networkinfoId)
	{
		this.networkinfoId = networkinfoId;
		setNetworkinfoIdModified( true );
	}

	/** 
	 * Sets the value of networkinfoIdModified
	 */
	public void setNetworkinfoIdModified(boolean networkinfoIdModified)
	{
		this.networkinfoIdModified = networkinfoIdModified;
	}

	/** 
	 * Gets the value of networkinfoIdModified
	 */
	public boolean isNetworkinfoIdModified()
	{
		return networkinfoIdModified;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
		setNameModified( true );
	}

	/** 
	 * Sets the value of nameModified
	 */
	public void setNameModified(boolean nameModified)
	{
		this.nameModified = nameModified;
	}

	/** 
	 * Gets the value of nameModified
	 */
	public boolean isNameModified()
	{
		return nameModified;
	}

	/**
	 * Method 'getCmdline'
	 * 
	 * @return String
	 */
	public String getCmdline()
	{
		return cmdline;
	}

	/**
	 * Method 'setCmdline'
	 * 
	 * @param cmdline
	 */
	public void setCmdline(String cmdline)
	{
		this.cmdline = cmdline;
		setCmdlineModified( true );
	}

	/** 
	 * Sets the value of cmdlineModified
	 */
	public void setCmdlineModified(boolean cmdlineModified)
	{
		this.cmdlineModified = cmdlineModified;
	}

	/** 
	 * Gets the value of cmdlineModified
	 */
	public boolean isCmdlineModified()
	{
		return cmdlineModified;
	}

	/**
	 * Method 'getResult'
	 * 
	 * @return String
	 */
	public String getResult()
	{
		return result;
	}

	/**
	 * Method 'setResult'
	 * 
	 * @param result
	 */
	public void setResult(String result)
	{
		this.result = result;
		setResultModified( true );
	}

	/** 
	 * Sets the value of resultModified
	 */
	public void setResultModified(boolean resultModified)
	{
		this.resultModified = resultModified;
	}

	/** 
	 * Gets the value of resultModified
	 */
	public boolean isResultModified()
	{
		return resultModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Clqinfo)) {
			return false;
		}
		
		final Clqinfo _cast = (Clqinfo) _other;
		if (clqinfoId != _cast.clqinfoId) {
			return false;
		}
		
		if (clqinfoIdModified != _cast.clqinfoIdModified) {
			return false;
		}
		
		if (networkinfoId != _cast.networkinfoId) {
			return false;
		}
		
		if (networkinfoIdModified != _cast.networkinfoIdModified) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (nameModified != _cast.nameModified) {
			return false;
		}
		
		if (cmdline == null ? _cast.cmdline != cmdline : !cmdline.equals( _cast.cmdline )) {
			return false;
		}
		
		if (cmdlineModified != _cast.cmdlineModified) {
			return false;
		}
		
		if (result == null ? _cast.result != result : !result.equals( _cast.result )) {
			return false;
		}
		
		if (resultModified != _cast.resultModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (clqinfoId ^ (clqinfoId >>> 32));
		_hashCode = 29 * _hashCode + (clqinfoIdModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) (networkinfoId ^ (networkinfoId >>> 32));
		_hashCode = 29 * _hashCode + (networkinfoIdModified ? 1 : 0);
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nameModified ? 1 : 0);
		if (cmdline != null) {
			_hashCode = 29 * _hashCode + cmdline.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (cmdlineModified ? 1 : 0);
		if (result != null) {
			_hashCode = 29 * _hashCode + result.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (resultModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ClqinfoPk
	 */
	public ClqinfoPk createPk()
	{
		return new ClqinfoPk(clqinfoId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nhcsys.dataaccess.dto.Clqinfo: " );
		ret.append( "clqinfoId=" + clqinfoId );
		ret.append( ", networkinfoId=" + networkinfoId );
		ret.append( ", name=" + name );
		ret.append( ", cmdline=" + cmdline );
		ret.append( ", result=" + result );
		return ret.toString();
	}

}
