/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.dto;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class ModifiedData implements Serializable
{
	/** 
	 * This attribute maps to the column MODIFIED_DATA_ID in the MODIFIED_DATA table.
	 */
	private long modifiedDataId;

	/** 
	 * This attribute represents whether the attribute modifiedDataId has been modified since being read from the database.
	 */
	private boolean modifiedDataIdModified = false;

	/** 
	 * This attribute maps to the column CUSTOMER_ID in the MODIFIED_DATA table.
	 */
	private long customerId;

	/** 
	 * This attribute represents whether the attribute customerId has been modified since being read from the database.
	 */
	private boolean customerIdModified = false;

	/** 
	 * This attribute maps to the column MODIFIED_TIME in the MODIFIED_DATA table.
	 */
	private Date modifiedTime;

	/** 
	 * This attribute represents whether the attribute modifiedTime has been modified since being read from the database.
	 */
	private boolean modifiedTimeModified = false;

	/**
	 * Method 'ModifiedData'
	 * 
	 */
	public ModifiedData()
	{
	}

	/**
	 * Method 'getModifiedDataId'
	 * 
	 * @return long
	 */
	public long getModifiedDataId()
	{
		return modifiedDataId;
	}

	/**
	 * Method 'setModifiedDataId'
	 * 
	 * @param modifiedDataId
	 */
	public void setModifiedDataId(long modifiedDataId)
	{
		this.modifiedDataId = modifiedDataId;
		setModifiedDataIdModified( true );
	}

	/** 
	 * Sets the value of modifiedDataIdModified
	 */
	public void setModifiedDataIdModified(boolean modifiedDataIdModified)
	{
		this.modifiedDataIdModified = modifiedDataIdModified;
	}

	/** 
	 * Gets the value of modifiedDataIdModified
	 */
	public boolean isModifiedDataIdModified()
	{
		return modifiedDataIdModified;
	}

	/**
	 * Method 'getCustomerId'
	 * 
	 * @return long
	 */
	public long getCustomerId()
	{
		return customerId;
	}

	/**
	 * Method 'setCustomerId'
	 * 
	 * @param customerId
	 */
	public void setCustomerId(long customerId)
	{
		this.customerId = customerId;
		setCustomerIdModified( true );
	}

	/** 
	 * Sets the value of customerIdModified
	 */
	public void setCustomerIdModified(boolean customerIdModified)
	{
		this.customerIdModified = customerIdModified;
	}

	/** 
	 * Gets the value of customerIdModified
	 */
	public boolean isCustomerIdModified()
	{
		return customerIdModified;
	}

	/**
	 * Method 'getModifiedTime'
	 * 
	 * @return Date
	 */
	public Date getModifiedTime()
	{
		return modifiedTime;
	}

	/**
	 * Method 'setModifiedTime'
	 * 
	 * @param modifiedTime
	 */
	public void setModifiedTime(Date modifiedTime)
	{
		this.modifiedTime = modifiedTime;
		setModifiedTimeModified( true );
	}

	/** 
	 * Sets the value of modifiedTimeModified
	 */
	public void setModifiedTimeModified(boolean modifiedTimeModified)
	{
		this.modifiedTimeModified = modifiedTimeModified;
	}

	/** 
	 * Gets the value of modifiedTimeModified
	 */
	public boolean isModifiedTimeModified()
	{
		return modifiedTimeModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ModifiedData)) {
			return false;
		}
		
		final ModifiedData _cast = (ModifiedData) _other;
		if (modifiedDataId != _cast.modifiedDataId) {
			return false;
		}
		
		if (modifiedDataIdModified != _cast.modifiedDataIdModified) {
			return false;
		}
		
		if (customerId != _cast.customerId) {
			return false;
		}
		
		if (customerIdModified != _cast.customerIdModified) {
			return false;
		}
		
		if (modifiedTime == null ? _cast.modifiedTime != modifiedTime : !modifiedTime.equals( _cast.modifiedTime )) {
			return false;
		}
		
		if (modifiedTimeModified != _cast.modifiedTimeModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (modifiedDataId ^ (modifiedDataId >>> 32));
		_hashCode = 29 * _hashCode + (modifiedDataIdModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) (customerId ^ (customerId >>> 32));
		_hashCode = 29 * _hashCode + (customerIdModified ? 1 : 0);
		if (modifiedTime != null) {
			_hashCode = 29 * _hashCode + modifiedTime.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (modifiedTimeModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ModifiedDataPk
	 */
	public ModifiedDataPk createPk()
	{
		return new ModifiedDataPk(modifiedDataId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nhcsys.dataaccess.dto.ModifiedData: " );
		ret.append( "modifiedDataId=" + modifiedDataId );
		ret.append( ", customerId=" + customerId );
		ret.append( ", modifiedTime=" + modifiedTime );
		return ret.toString();
	}

}
