/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.dto;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class TelesalesCallSource implements Serializable
{
	/** 
	 * This attribute maps to the column SOURCE_ID in the TELESALES_CALL_SOURCE table.
	 */
	private long sourceId;

	/** 
	 * This attribute represents whether the attribute sourceId has been modified since being read from the database.
	 */
	private boolean sourceIdModified = false;

	/** 
	 * This attribute maps to the column SOURCE_DESC in the TELESALES_CALL_SOURCE table.
	 */
	private String sourceDesc;

	/** 
	 * This attribute represents whether the attribute sourceDesc has been modified since being read from the database.
	 */
	private boolean sourceDescModified = false;

	/**
	 * Method 'TelesalesCallSource'
	 * 
	 */
	public TelesalesCallSource()
	{
	}

	/**
	 * Method 'getSourceId'
	 * 
	 * @return long
	 */
	public long getSourceId()
	{
		return sourceId;
	}

	/**
	 * Method 'setSourceId'
	 * 
	 * @param sourceId
	 */
	public void setSourceId(long sourceId)
	{
		this.sourceId = sourceId;
		setSourceIdModified( true );
	}

	/** 
	 * Sets the value of sourceIdModified
	 */
	public void setSourceIdModified(boolean sourceIdModified)
	{
		this.sourceIdModified = sourceIdModified;
	}

	/** 
	 * Gets the value of sourceIdModified
	 */
	public boolean isSourceIdModified()
	{
		return sourceIdModified;
	}

	/**
	 * Method 'getSourceDesc'
	 * 
	 * @return String
	 */
	public String getSourceDesc()
	{
		return sourceDesc;
	}

	/**
	 * Method 'setSourceDesc'
	 * 
	 * @param sourceDesc
	 */
	public void setSourceDesc(String sourceDesc)
	{
		this.sourceDesc = sourceDesc;
		setSourceDescModified( true );
	}

	/** 
	 * Sets the value of sourceDescModified
	 */
	public void setSourceDescModified(boolean sourceDescModified)
	{
		this.sourceDescModified = sourceDescModified;
	}

	/** 
	 * Gets the value of sourceDescModified
	 */
	public boolean isSourceDescModified()
	{
		return sourceDescModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TelesalesCallSource)) {
			return false;
		}
		
		final TelesalesCallSource _cast = (TelesalesCallSource) _other;
		if (sourceId != _cast.sourceId) {
			return false;
		}
		
		if (sourceIdModified != _cast.sourceIdModified) {
			return false;
		}
		
		if (sourceDesc == null ? _cast.sourceDesc != sourceDesc : !sourceDesc.equals( _cast.sourceDesc )) {
			return false;
		}
		
		if (sourceDescModified != _cast.sourceDescModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (sourceId ^ (sourceId >>> 32));
		_hashCode = 29 * _hashCode + (sourceIdModified ? 1 : 0);
		if (sourceDesc != null) {
			_hashCode = 29 * _hashCode + sourceDesc.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (sourceDescModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TelesalesCallSourcePk
	 */
	public TelesalesCallSourcePk createPk()
	{
		return new TelesalesCallSourcePk(sourceId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nhcsys.dataaccess.dto.TelesalesCallSource: " );
		ret.append( "sourceId=" + sourceId );
		ret.append( ", sourceDesc=" + sourceDesc );
		return ret.toString();
	}

}
