/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.dto;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class TelesalesOrgs implements Serializable
{
	/** 
	 * This attribute maps to the column ORG_ID in the TELESALES_ORGS table.
	 */
	private long orgId;

	/** 
	 * This attribute represents whether the attribute orgId has been modified since being read from the database.
	 */
	private boolean orgIdModified = false;

	/** 
	 * This attribute maps to the column ORG_NAME in the TELESALES_ORGS table.
	 */
	private String orgName;

	/** 
	 * This attribute represents whether the attribute orgName has been modified since being read from the database.
	 */
	private boolean orgNameModified = false;

	/** 
	 * This attribute maps to the column CONFIG_VALUE in the TELESALES_ORGS table.
	 */
	private String configValue;

	/** 
	 * This attribute represents whether the attribute configValue has been modified since being read from the database.
	 */
	private boolean configValueModified = false;

	/**
	 * Method 'TelesalesOrgs'
	 * 
	 */
	public TelesalesOrgs()
	{
	}

	/**
	 * Method 'getOrgId'
	 * 
	 * @return long
	 */
	public long getOrgId()
	{
		return orgId;
	}

	/**
	 * Method 'setOrgId'
	 * 
	 * @param orgId
	 */
	public void setOrgId(long orgId)
	{
		this.orgId = orgId;
		setOrgIdModified( true );
	}

	/** 
	 * Sets the value of orgIdModified
	 */
	public void setOrgIdModified(boolean orgIdModified)
	{
		this.orgIdModified = orgIdModified;
	}

	/** 
	 * Gets the value of orgIdModified
	 */
	public boolean isOrgIdModified()
	{
		return orgIdModified;
	}

	/**
	 * Method 'getOrgName'
	 * 
	 * @return String
	 */
	public String getOrgName()
	{
		return orgName;
	}

	/**
	 * Method 'setOrgName'
	 * 
	 * @param orgName
	 */
	public void setOrgName(String orgName)
	{
		this.orgName = orgName;
		setOrgNameModified( true );
	}

	/** 
	 * Sets the value of orgNameModified
	 */
	public void setOrgNameModified(boolean orgNameModified)
	{
		this.orgNameModified = orgNameModified;
	}

	/** 
	 * Gets the value of orgNameModified
	 */
	public boolean isOrgNameModified()
	{
		return orgNameModified;
	}

	/**
	 * Method 'getConfigValue'
	 * 
	 * @return String
	 */
	public String getConfigValue()
	{
		return configValue;
	}

	/**
	 * Method 'setConfigValue'
	 * 
	 * @param configValue
	 */
	public void setConfigValue(String configValue)
	{
		this.configValue = configValue;
		setConfigValueModified( true );
	}

	/** 
	 * Sets the value of configValueModified
	 */
	public void setConfigValueModified(boolean configValueModified)
	{
		this.configValueModified = configValueModified;
	}

	/** 
	 * Gets the value of configValueModified
	 */
	public boolean isConfigValueModified()
	{
		return configValueModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TelesalesOrgs)) {
			return false;
		}
		
		final TelesalesOrgs _cast = (TelesalesOrgs) _other;
		if (orgId != _cast.orgId) {
			return false;
		}
		
		if (orgIdModified != _cast.orgIdModified) {
			return false;
		}
		
		if (orgName == null ? _cast.orgName != orgName : !orgName.equals( _cast.orgName )) {
			return false;
		}
		
		if (orgNameModified != _cast.orgNameModified) {
			return false;
		}
		
		if (configValue == null ? _cast.configValue != configValue : !configValue.equals( _cast.configValue )) {
			return false;
		}
		
		if (configValueModified != _cast.configValueModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (orgId ^ (orgId >>> 32));
		_hashCode = 29 * _hashCode + (orgIdModified ? 1 : 0);
		if (orgName != null) {
			_hashCode = 29 * _hashCode + orgName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (orgNameModified ? 1 : 0);
		if (configValue != null) {
			_hashCode = 29 * _hashCode + configValue.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (configValueModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TelesalesOrgsPk
	 */
	public TelesalesOrgsPk createPk()
	{
		return new TelesalesOrgsPk(orgId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nhcsys.dataaccess.dto.TelesalesOrgs: " );
		ret.append( "orgId=" + orgId );
		ret.append( ", orgName=" + orgName );
		ret.append( ", configValue=" + configValue );
		return ret.toString();
	}

}
