/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the TELESALES_ORGS table.
 */
public class TelesalesOrgsPk implements Serializable
{
	private long orgId;

	/** 
	 * This attribute represents whether the primitive attribute orgId is null.
	 */
	private boolean orgIdNull;

	/** 
	 * Sets the value of orgId
	 */
	public void setOrgId(long orgId)
	{
		this.orgId = orgId;
	}

	/** 
	 * Gets the value of orgId
	 */
	public long getOrgId()
	{
		return orgId;
	}

	/**
	 * Method 'TelesalesOrgsPk'
	 * 
	 */
	public TelesalesOrgsPk()
	{
	}

	/**
	 * Method 'TelesalesOrgsPk'
	 * 
	 * @param orgId
	 */
	public TelesalesOrgsPk(final long orgId)
	{
		this.orgId = orgId;
	}

	/** 
	 * Sets the value of orgIdNull
	 */
	public void setOrgIdNull(boolean orgIdNull)
	{
		this.orgIdNull = orgIdNull;
	}

	/** 
	 * Gets the value of orgIdNull
	 */
	public boolean isOrgIdNull()
	{
		return orgIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TelesalesOrgsPk)) {
			return false;
		}
		
		final TelesalesOrgsPk _cast = (TelesalesOrgsPk) _other;
		if (orgId != _cast.orgId) {
			return false;
		}
		
		if (orgIdNull != _cast.orgIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (orgId ^ (orgId >>> 32));
		_hashCode = 29 * _hashCode + (orgIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nhcsys.dataaccess.dto.TelesalesOrgsPk: " );
		ret.append( "orgId=" + orgId );
		return ret.toString();
	}

}
