/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.dto;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class UpdateStatus implements Serializable
{
	/** 
	 * This attribute maps to the column UPDATE_STATUS_ID in the UPDATE_STATUS table.
	 */
	private long updateStatusId;

	/** 
	 * This attribute represents whether the attribute updateStatusId has been modified since being read from the database.
	 */
	private boolean updateStatusIdModified = false;

	/** 
	 * This attribute maps to the column SESSION_ID in the UPDATE_STATUS table.
	 */
	private String sessionId;

	/** 
	 * This attribute represents whether the attribute sessionId has been modified since being read from the database.
	 */
	private boolean sessionIdModified = false;

	/** 
	 * This attribute maps to the column MACHINE_ID in the UPDATE_STATUS table.
	 */
	private long machineId;

	/** 
	 * This attribute represents whether the attribute machineId has been modified since being read from the database.
	 */
	private boolean machineIdModified = false;

	/** 
	 * This attribute maps to the column PRODUCT_ID in the UPDATE_STATUS table.
	 */
	private String productId;

	/** 
	 * This attribute represents whether the attribute productId has been modified since being read from the database.
	 */
	private boolean productIdModified = false;

	/** 
	 * This attribute maps to the column DESCRIPTION in the UPDATE_STATUS table.
	 */
	private String description;

	/** 
	 * This attribute represents whether the attribute description has been modified since being read from the database.
	 */
	private boolean descriptionModified = false;

	/** 
	 * This attribute maps to the column REPORT in the UPDATE_STATUS table.
	 */
	private String report;

	/** 
	 * This attribute represents whether the attribute report has been modified since being read from the database.
	 */
	private boolean reportModified = false;

	/** 
	 * This attribute maps to the column STATUS in the UPDATE_STATUS table.
	 */
	private String status;

	/** 
	 * This attribute represents whether the attribute status has been modified since being read from the database.
	 */
	private boolean statusModified = false;

	/**
	 * Method 'UpdateStatus'
	 * 
	 */
	public UpdateStatus()
	{
	}

	/**
	 * Method 'getUpdateStatusId'
	 * 
	 * @return long
	 */
	public long getUpdateStatusId()
	{
		return updateStatusId;
	}

	/**
	 * Method 'setUpdateStatusId'
	 * 
	 * @param updateStatusId
	 */
	public void setUpdateStatusId(long updateStatusId)
	{
		this.updateStatusId = updateStatusId;
		setUpdateStatusIdModified( true );
	}

	/** 
	 * Sets the value of updateStatusIdModified
	 */
	public void setUpdateStatusIdModified(boolean updateStatusIdModified)
	{
		this.updateStatusIdModified = updateStatusIdModified;
	}

	/** 
	 * Gets the value of updateStatusIdModified
	 */
	public boolean isUpdateStatusIdModified()
	{
		return updateStatusIdModified;
	}

	/**
	 * Method 'getSessionId'
	 * 
	 * @return String
	 */
	public String getSessionId()
	{
		return sessionId;
	}

	/**
	 * Method 'setSessionId'
	 * 
	 * @param sessionId
	 */
	public void setSessionId(String sessionId)
	{
		this.sessionId = sessionId;
		setSessionIdModified( true );
	}

	/** 
	 * Sets the value of sessionIdModified
	 */
	public void setSessionIdModified(boolean sessionIdModified)
	{
		this.sessionIdModified = sessionIdModified;
	}

	/** 
	 * Gets the value of sessionIdModified
	 */
	public boolean isSessionIdModified()
	{
		return sessionIdModified;
	}

	/**
	 * Method 'getMachineId'
	 * 
	 * @return long
	 */
	public long getMachineId()
	{
		return machineId;
	}

	/**
	 * Method 'setMachineId'
	 * 
	 * @param machineId
	 */
	public void setMachineId(long machineId)
	{
		this.machineId = machineId;
		setMachineIdModified( true );
	}

	/** 
	 * Sets the value of machineIdModified
	 */
	public void setMachineIdModified(boolean machineIdModified)
	{
		this.machineIdModified = machineIdModified;
	}

	/** 
	 * Gets the value of machineIdModified
	 */
	public boolean isMachineIdModified()
	{
		return machineIdModified;
	}

	/**
	 * Method 'getProductId'
	 * 
	 * @return String
	 */
	public String getProductId()
	{
		return productId;
	}

	/**
	 * Method 'setProductId'
	 * 
	 * @param productId
	 */
	public void setProductId(String productId)
	{
		this.productId = productId;
		setProductIdModified( true );
	}

	/** 
	 * Sets the value of productIdModified
	 */
	public void setProductIdModified(boolean productIdModified)
	{
		this.productIdModified = productIdModified;
	}

	/** 
	 * Gets the value of productIdModified
	 */
	public boolean isProductIdModified()
	{
		return productIdModified;
	}

	/**
	 * Method 'getDescription'
	 * 
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method 'setDescription'
	 * 
	 * @param description
	 */
	public void setDescription(String description)
	{
		this.description = description;
		setDescriptionModified( true );
	}

	/** 
	 * Sets the value of descriptionModified
	 */
	public void setDescriptionModified(boolean descriptionModified)
	{
		this.descriptionModified = descriptionModified;
	}

	/** 
	 * Gets the value of descriptionModified
	 */
	public boolean isDescriptionModified()
	{
		return descriptionModified;
	}

	/**
	 * Method 'getReport'
	 * 
	 * @return String
	 */
	public String getReport()
	{
		return report;
	}

	/**
	 * Method 'setReport'
	 * 
	 * @param report
	 */
	public void setReport(String report)
	{
		this.report = report;
		setReportModified( true );
	}

	/** 
	 * Sets the value of reportModified
	 */
	public void setReportModified(boolean reportModified)
	{
		this.reportModified = reportModified;
	}

	/** 
	 * Gets the value of reportModified
	 */
	public boolean isReportModified()
	{
		return reportModified;
	}

	/**
	 * Method 'getStatus'
	 * 
	 * @return String
	 */
	public String getStatus()
	{
		return status;
	}

	/**
	 * Method 'setStatus'
	 * 
	 * @param status
	 */
	public void setStatus(String status)
	{
		this.status = status;
		setStatusModified( true );
	}

	/** 
	 * Sets the value of statusModified
	 */
	public void setStatusModified(boolean statusModified)
	{
		this.statusModified = statusModified;
	}

	/** 
	 * Gets the value of statusModified
	 */
	public boolean isStatusModified()
	{
		return statusModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UpdateStatus)) {
			return false;
		}
		
		final UpdateStatus _cast = (UpdateStatus) _other;
		if (updateStatusId != _cast.updateStatusId) {
			return false;
		}
		
		if (updateStatusIdModified != _cast.updateStatusIdModified) {
			return false;
		}
		
		if (sessionId == null ? _cast.sessionId != sessionId : !sessionId.equals( _cast.sessionId )) {
			return false;
		}
		
		if (sessionIdModified != _cast.sessionIdModified) {
			return false;
		}
		
		if (machineId != _cast.machineId) {
			return false;
		}
		
		if (machineIdModified != _cast.machineIdModified) {
			return false;
		}
		
		if (productId == null ? _cast.productId != productId : !productId.equals( _cast.productId )) {
			return false;
		}
		
		if (productIdModified != _cast.productIdModified) {
			return false;
		}
		
		if (description == null ? _cast.description != description : !description.equals( _cast.description )) {
			return false;
		}
		
		if (descriptionModified != _cast.descriptionModified) {
			return false;
		}
		
		if (report == null ? _cast.report != report : !report.equals( _cast.report )) {
			return false;
		}
		
		if (reportModified != _cast.reportModified) {
			return false;
		}
		
		if (status == null ? _cast.status != status : !status.equals( _cast.status )) {
			return false;
		}
		
		if (statusModified != _cast.statusModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (updateStatusId ^ (updateStatusId >>> 32));
		_hashCode = 29 * _hashCode + (updateStatusIdModified ? 1 : 0);
		if (sessionId != null) {
			_hashCode = 29 * _hashCode + sessionId.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (sessionIdModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) (machineId ^ (machineId >>> 32));
		_hashCode = 29 * _hashCode + (machineIdModified ? 1 : 0);
		if (productId != null) {
			_hashCode = 29 * _hashCode + productId.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (productIdModified ? 1 : 0);
		if (description != null) {
			_hashCode = 29 * _hashCode + description.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (descriptionModified ? 1 : 0);
		if (report != null) {
			_hashCode = 29 * _hashCode + report.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (reportModified ? 1 : 0);
		if (status != null) {
			_hashCode = 29 * _hashCode + status.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (statusModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UpdateStatusPk
	 */
	public UpdateStatusPk createPk()
	{
		return new UpdateStatusPk(updateStatusId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nhcsys.dataaccess.dto.UpdateStatus: " );
		ret.append( "updateStatusId=" + updateStatusId );
		ret.append( ", sessionId=" + sessionId );
		ret.append( ", machineId=" + machineId );
		ret.append( ", productId=" + productId );
		ret.append( ", description=" + description );
		ret.append( ", report=" + report );
		ret.append( ", status=" + status );
		return ret.toString();
	}

}
