/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.dto;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Wmiqinfo implements Serializable
{
	/** 
	 * This attribute maps to the column WMIQINFO_ID in the WMIQINFO table.
	 */
	private long wmiqinfoId;

	/** 
	 * This attribute represents whether the attribute wmiqinfoId has been modified since being read from the database.
	 */
	private boolean wmiqinfoIdModified = false;

	/** 
	 * This attribute maps to the column NETWORKINFO_ID in the WMIQINFO table.
	 */
	private long networkinfoId;

	/** 
	 * This attribute represents whether the attribute networkinfoId has been modified since being read from the database.
	 */
	private boolean networkinfoIdModified = false;

	/** 
	 * This attribute maps to the column NAME in the WMIQINFO table.
	 */
	private String name;

	/** 
	 * This attribute represents whether the attribute name has been modified since being read from the database.
	 */
	private boolean nameModified = false;

	/** 
	 * This attribute maps to the column QUERY in the WMIQINFO table.
	 */
	private String query;

	/** 
	 * This attribute represents whether the attribute query has been modified since being read from the database.
	 */
	private boolean queryModified = false;

	/** 
	 * This attribute maps to the column RESULT in the WMIQINFO table.
	 */
	private String result;

	/** 
	 * This attribute represents whether the attribute result has been modified since being read from the database.
	 */
	private boolean resultModified = false;

	/**
	 * Method 'Wmiqinfo'
	 * 
	 */
	public Wmiqinfo()
	{
	}

	/**
	 * Method 'getWmiqinfoId'
	 * 
	 * @return long
	 */
	public long getWmiqinfoId()
	{
		return wmiqinfoId;
	}

	/**
	 * Method 'setWmiqinfoId'
	 * 
	 * @param wmiqinfoId
	 */
	public void setWmiqinfoId(long wmiqinfoId)
	{
		this.wmiqinfoId = wmiqinfoId;
		setWmiqinfoIdModified( true );
	}

	/** 
	 * Sets the value of wmiqinfoIdModified
	 */
	public void setWmiqinfoIdModified(boolean wmiqinfoIdModified)
	{
		this.wmiqinfoIdModified = wmiqinfoIdModified;
	}

	/** 
	 * Gets the value of wmiqinfoIdModified
	 */
	public boolean isWmiqinfoIdModified()
	{
		return wmiqinfoIdModified;
	}

	/**
	 * Method 'getNetworkinfoId'
	 * 
	 * @return long
	 */
	public long getNetworkinfoId()
	{
		return networkinfoId;
	}

	/**
	 * Method 'setNetworkinfoId'
	 * 
	 * @param networkinfoId
	 */
	public void setNetworkinfoId(long networkinfoId)
	{
		this.networkinfoId = networkinfoId;
		setNetworkinfoIdModified( true );
	}

	/** 
	 * Sets the value of networkinfoIdModified
	 */
	public void setNetworkinfoIdModified(boolean networkinfoIdModified)
	{
		this.networkinfoIdModified = networkinfoIdModified;
	}

	/** 
	 * Gets the value of networkinfoIdModified
	 */
	public boolean isNetworkinfoIdModified()
	{
		return networkinfoIdModified;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
		setNameModified( true );
	}

	/** 
	 * Sets the value of nameModified
	 */
	public void setNameModified(boolean nameModified)
	{
		this.nameModified = nameModified;
	}

	/** 
	 * Gets the value of nameModified
	 */
	public boolean isNameModified()
	{
		return nameModified;
	}

	/**
	 * Method 'getQuery'
	 * 
	 * @return String
	 */
	public String getQuery()
	{
		return query;
	}

	/**
	 * Method 'setQuery'
	 * 
	 * @param query
	 */
	public void setQuery(String query)
	{
		this.query = query;
		setQueryModified( true );
	}

	/** 
	 * Sets the value of queryModified
	 */
	public void setQueryModified(boolean queryModified)
	{
		this.queryModified = queryModified;
	}

	/** 
	 * Gets the value of queryModified
	 */
	public boolean isQueryModified()
	{
		return queryModified;
	}

	/**
	 * Method 'getResult'
	 * 
	 * @return String
	 */
	public String getResult()
	{
		return result;
	}

	/**
	 * Method 'setResult'
	 * 
	 * @param result
	 */
	public void setResult(String result)
	{
		this.result = result;
		setResultModified( true );
	}

	/** 
	 * Sets the value of resultModified
	 */
	public void setResultModified(boolean resultModified)
	{
		this.resultModified = resultModified;
	}

	/** 
	 * Gets the value of resultModified
	 */
	public boolean isResultModified()
	{
		return resultModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Wmiqinfo)) {
			return false;
		}
		
		final Wmiqinfo _cast = (Wmiqinfo) _other;
		if (wmiqinfoId != _cast.wmiqinfoId) {
			return false;
		}
		
		if (wmiqinfoIdModified != _cast.wmiqinfoIdModified) {
			return false;
		}
		
		if (networkinfoId != _cast.networkinfoId) {
			return false;
		}
		
		if (networkinfoIdModified != _cast.networkinfoIdModified) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (nameModified != _cast.nameModified) {
			return false;
		}
		
		if (query == null ? _cast.query != query : !query.equals( _cast.query )) {
			return false;
		}
		
		if (queryModified != _cast.queryModified) {
			return false;
		}
		
		if (result == null ? _cast.result != result : !result.equals( _cast.result )) {
			return false;
		}
		
		if (resultModified != _cast.resultModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (wmiqinfoId ^ (wmiqinfoId >>> 32));
		_hashCode = 29 * _hashCode + (wmiqinfoIdModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) (networkinfoId ^ (networkinfoId >>> 32));
		_hashCode = 29 * _hashCode + (networkinfoIdModified ? 1 : 0);
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nameModified ? 1 : 0);
		if (query != null) {
			_hashCode = 29 * _hashCode + query.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (queryModified ? 1 : 0);
		if (result != null) {
			_hashCode = 29 * _hashCode + result.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (resultModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return WmiqinfoPk
	 */
	public WmiqinfoPk createPk()
	{
		return new WmiqinfoPk(wmiqinfoId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nhcsys.dataaccess.dto.Wmiqinfo: " );
		ret.append( "wmiqinfoId=" + wmiqinfoId );
		ret.append( ", networkinfoId=" + networkinfoId );
		ret.append( ", name=" + name );
		ret.append( ", query=" + query );
		ret.append( ", result=" + result );
		return ret.toString();
	}

}
