/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nhcsys.dataaccess.jdbc;

import com.nhcsys.dataaccess.dao.*;
import com.nhcsys.dataaccess.factory.*;
import com.nhcsys.dataaccess.dto.*;
import com.nhcsys.dataaccess.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ClqinfoDaoImpl extends AbstractDAO implements ClqinfoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( ClqinfoDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT CLQINFO_ID, NETWORKINFO_ID, NAME, CMDLINE, RESULT FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	private int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( CLQINFO_ID, NETWORKINFO_ID, NAME, CMDLINE, RESULT ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET CLQINFO_ID = ?, NETWORKINFO_ID = ?, NAME = ?, CMDLINE = ?, RESULT = ? WHERE CLQINFO_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE CLQINFO_ID = ?";

	/** 
	 * Index of column CLQINFO_ID
	 */
	protected static final int COLUMN_CLQINFO_ID = 1;

	/** 
	 * Index of column NETWORKINFO_ID
	 */
	protected static final int COLUMN_NETWORKINFO_ID = 2;

	/** 
	 * Index of column NAME
	 */
	protected static final int COLUMN_NAME = 3;

	/** 
	 * Index of column CMDLINE
	 */
	protected static final int COLUMN_CMDLINE = 4;

	/** 
	 * Index of column RESULT
	 */
	protected static final int COLUMN_RESULT = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column CLQINFO_ID
	 */
	protected static final int PK_COLUMN_CLQINFO_ID = 1;

	/** 
	 * Inserts a new row in the CLQINFO table.
	 */
	public ClqinfoPk insert(Clqinfo dto) throws ClqinfoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( "SELECT clqinfo_id_seq.NEXTVAL FROM DUAL" );
			rs = stmt.executeQuery();
			if (rs.next()) {
				dto.setClqinfoId( rs.getLong( 1 ) );
				rs.close();
				stmt.close();
			}
		
			StringBuffer sql = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isClqinfoIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "CLQINFO_ID" );
				modifiedCount++;
			}
		
			if (dto.isNetworkinfoIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "NETWORKINFO_ID" );
				modifiedCount++;
			}
		
			if (dto.isNameModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "NAME" );
				modifiedCount++;
			}
		
			if (dto.isCmdlineModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "CMDLINE" );
				modifiedCount++;
			}
		
			if (dto.isResultModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
				}
		
				sql.append( "RESULT" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			for (int i=0; i<modifiedCount; i++ ) {
				if (i>0) {
					sql.append( "," );
				}
		
				sql.append( "?" );
			}
		
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isClqinfoIdModified()) {
				stmt.setLong( index++, dto.getClqinfoId() );
			}
		
			if (dto.isNetworkinfoIdModified()) {
				stmt.setLong( index++, dto.getNetworkinfoId() );
			}
		
			if (dto.isNameModified()) {
				stmt.setString( index++, dto.getName() );
			}
		
			if (dto.isCmdlineModified()) {
				stmt.setString( index++, dto.getCmdline() );
			}
		
			if (dto.isResultModified()) {
				stmt.setString( index++, dto.getResult() );
			}
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ClqinfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the CLQINFO table.
	 */
	public void update(ClqinfoPk pk, Clqinfo dto) throws ClqinfoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isClqinfoIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CLQINFO_ID=?" );
				modified=true;
			}
		
			if (dto.isNetworkinfoIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "NETWORKINFO_ID=?" );
				modified=true;
			}
		
			if (dto.isNameModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "NAME=?" );
				modified=true;
			}
		
			if (dto.isCmdlineModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CMDLINE=?" );
				modified=true;
			}
		
			if (dto.isResultModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "RESULT=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE CLQINFO_ID=?" );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isClqinfoIdModified()) {
				stmt.setLong( index++, dto.getClqinfoId() );
			}
		
			if (dto.isNetworkinfoIdModified()) {
				stmt.setLong( index++, dto.getNetworkinfoId() );
			}
		
			if (dto.isNameModified()) {
				stmt.setString( index++, dto.getName() );
			}
		
			if (dto.isCmdlineModified()) {
				stmt.setString( index++, dto.getCmdline() );
			}
		
			if (dto.isResultModified()) {
				stmt.setString( index++, dto.getResult() );
			}
		
			stmt.setLong( index++, pk.getClqinfoId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ClqinfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the CLQINFO table.
	 */
	public void delete(ClqinfoPk pk) throws ClqinfoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getClqinfoId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ClqinfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the CLQINFO table that matches the specified primary-key value.
	 */
	public Clqinfo findByPrimaryKey(ClqinfoPk pk) throws ClqinfoDaoException
	{
		return findByPrimaryKey( pk.getClqinfoId() );
	}

	/** 
	 * Returns all rows from the CLQINFO table that match the criteria 'CLQINFO_ID = :clqinfoId'.
	 */
	public Clqinfo findByPrimaryKey(long clqinfoId) throws ClqinfoDaoException
	{
		Clqinfo ret[] = findByDynamicSelect( SQL_SELECT + " WHERE CLQINFO_ID = ?", new Object[] {  new Long(clqinfoId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the CLQINFO table that match the criteria ''.
	 */
	public Clqinfo[] findAll() throws ClqinfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY CLQINFO_ID", null );
	}

	/** 
	 * Returns all rows from the CLQINFO table that match the criteria 'CLQINFO_ID = :clqinfoId'.
	 */
	public Clqinfo[] findWhereClqinfoIdEquals(long clqinfoId) throws ClqinfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CLQINFO_ID = ? ORDER BY CLQINFO_ID", new Object[] {  new Long(clqinfoId) } );
	}

	/** 
	 * Returns all rows from the CLQINFO table that match the criteria 'NETWORKINFO_ID = :networkinfoId'.
	 */
	public Clqinfo[] findWhereNetworkinfoIdEquals(long networkinfoId) throws ClqinfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NETWORKINFO_ID = ? ORDER BY NETWORKINFO_ID", new Object[] {  new Long(networkinfoId) } );
	}

	/** 
	 * Returns all rows from the CLQINFO table that match the criteria 'NAME = :name'.
	 */
	public Clqinfo[] findWhereNameEquals(String name) throws ClqinfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NAME = ? ORDER BY NAME", new Object[] { name } );
	}

	/** 
	 * Returns all rows from the CLQINFO table that match the criteria 'CMDLINE = :cmdline'.
	 */
	public Clqinfo[] findWhereCmdlineEquals(String cmdline) throws ClqinfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CMDLINE = ? ORDER BY CMDLINE", new Object[] { cmdline } );
	}

	/** 
	 * Returns all rows from the CLQINFO table that match the criteria 'RESULT = :result'.
	 */
	public Clqinfo[] findWhereResultEquals(String result) throws ClqinfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE RESULT = ? ORDER BY RESULT", new Object[] { result } );
	}

	/**
	 * Method 'ClqinfoDaoImpl'
	 * 
	 */
	public ClqinfoDaoImpl()
	{
	}

	/**
	 * Method 'ClqinfoDaoImpl'
	 * 
	 * @param userConn
	 */
	public ClqinfoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "CLQINFO";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Clqinfo fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Clqinfo dto = new Clqinfo();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Clqinfo[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Clqinfo dto = new Clqinfo();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Clqinfo ret[] = new Clqinfo[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Clqinfo dto, ResultSet rs) throws SQLException
	{
		dto.setClqinfoId( rs.getLong( COLUMN_CLQINFO_ID ) );
		dto.setNetworkinfoId( rs.getLong( COLUMN_NETWORKINFO_ID ) );
		dto.setName( rs.getString( COLUMN_NAME ) );
		dto.setCmdline( rs.getString( COLUMN_CMDLINE ) );
		dto.setResult( rs.getString( COLUMN_RESULT ) );
	}

	/** 
	 * Returns all rows from the CLQINFO table that match the specified arbitrary SQL statement
	 */
	public Clqinfo[] findByDynamicSelect(String sql, Object[] sqlParams) throws ClqinfoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ClqinfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the CLQINFO table that match the specified arbitrary SQL statement
	 */
	public Clqinfo[] findByDynamicWhere(String sql, Object[] sqlParams) throws ClqinfoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new ClqinfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
